import type { Locale } from "./i18n";
import { FIELD_DEFS } from "./import-engine/fields";

const keys = [
  "readUrl",
  "name",
  "description",
  "equipment",
  "organize",
  "readText",
  "sort",
  "uncertain",
  "review",
  "searchLink",
  "invalidLink",
  "anotherLink",
  "notEnough",
  "placeholder",
  "example",
  "languages",
  "reviewTitle",
  "reviewHelp",
  "importantMissing",
  "propertyName",
  "propertyPlaceholder",
  "photos",
  "photoAlt",
  "photoRights",
  "sourceSaved",
  "sourceText",
  "creating",
  "create",
  "manualReview",
  "fieldPrompt",
] as const;
const copy: Record<Locale, readonly string[]> = {
  fr: [
    "Lecture du logement",
    "Recherche du nom",
    "Recherche de la description",
    "Recherche des équipements",
    "Informations organisées",
    "Lecture de votre texte",
    "Tri par thème",
    "Détection des informations incertaines",
    "Préparation de la vérification",
    "Ce lien Airbnb correspond à une recherche. Ouvrez le logement voulu et copiez son lien.",
    "Ce lien ne semble pas complet. Copiez-le depuis la barre d’adresse.",
    "Essayer un autre lien",
    "Nous n’avons pas trouvé assez d’informations. Ajoutez du texte ou créez le logement manuellement.",
    "Vos notes, un message WhatsApp, un e-mail, le texte de votre annonce…",
    "Essayer avec un exemple",
    "Français, anglais, espagnol, allemand, italien et portugais sont reconnus.",
    "Voici ce que nous avons préparé",
    "Vérifiez avant de créer le logement. Rien de manquant n’est inventé.",
    "Informations importantes à compléter : {count}. Vous pourrez le faire juste après.",
    "Nom du logement",
    "Mon logement",
    "Photos détectées",
    "Photo issue de la source",
    "Importer ces photos : je dispose des droits pour les utiliser.",
    "Source conservée",
    "Voir le texte source",
    "Création…",
    "Créer ce logement",
    "Les champs corrigés ici sont validés manuellement.",
    "Renseignez : {label}",
  ],
  en: [
    "Reading the property",
    "Finding the name",
    "Finding the description",
    "Finding amenities",
    "Organizing information",
    "Reading your text",
    "Sorting by topic",
    "Detecting uncertain information",
    "Preparing your review",
    "This Airbnb link is a search page. Open the property you want and copy its link.",
    "This link appears incomplete. Copy it from the address bar.",
    "Try another link",
    "We could not find enough information. Add more text or create the property manually.",
    "Your notes, a WhatsApp message, an email, your listing text…",
    "Try an example",
    "French, English, Spanish, German, Italian and Portuguese are supported.",
    "Here is what we prepared",
    "Review before creating the property. Missing information is never invented.",
    "Important details to complete: {count}. You can add them next.",
    "Property name",
    "My property",
    "Photos found",
    "Photo from the source",
    "Import these photos: I have permission to use them.",
    "Source preserved",
    "View source text",
    "Creating…",
    "Create this property",
    "Fields edited here are marked as manually verified.",
    "Enter: {label}",
  ],
  es: [
    "Leyendo el alojamiento",
    "Buscando el nombre",
    "Buscando la descripción",
    "Buscando equipamiento",
    "Organizando información",
    "Leyendo tu texto",
    "Clasificando por tema",
    "Detectando información incierta",
    "Preparando la revisión",
    "Este enlace de Airbnb es una búsqueda. Abre el alojamiento y copia su enlace.",
    "Este enlace parece incompleto. Cópialo desde la barra de direcciones.",
    "Probar otro enlace",
    "No encontramos suficiente información. Añade texto o crea el alojamiento manualmente.",
    "Tus notas, un mensaje de WhatsApp, un correo, el texto de tu anuncio…",
    "Probar un ejemplo",
    "Se reconocen francés, inglés, español, alemán, italiano y portugués.",
    "Esto es lo que hemos preparado",
    "Revisa antes de crear el alojamiento. No inventamos información que falta.",
    "Datos importantes pendientes: {count}. Puedes completarlos después.",
    "Nombre del alojamiento",
    "Mi alojamiento",
    "Fotos detectadas",
    "Foto de la fuente",
    "Importar estas fotos: tengo permiso para utilizarlas.",
    "Fuente conservada",
    "Ver texto original",
    "Creando…",
    "Crear este alojamiento",
    "Los campos editados aquí se marcan como verificados manualmente.",
    "Introduce: {label}",
  ],
  de: [
    "Unterkunft wird gelesen",
    "Name wird gesucht",
    "Beschreibung wird gesucht",
    "Ausstattung wird gesucht",
    "Informationen werden geordnet",
    "Ihr Text wird gelesen",
    "Nach Themen sortieren",
    "Unklare Informationen erkennen",
    "Prüfung vorbereiten",
    "Dieser Airbnb-Link führt zu einer Suche. Öffnen Sie die Unterkunft und kopieren Sie deren Link.",
    "Dieser Link scheint unvollständig. Kopieren Sie ihn aus der Adressleiste.",
    "Anderen Link versuchen",
    "Nicht genug Informationen gefunden. Ergänzen Sie Text oder erstellen Sie die Unterkunft manuell.",
    "Ihre Notizen, eine WhatsApp-Nachricht, eine E-Mail, Ihr Inseratstext…",
    "Beispiel ausprobieren",
    "Französisch, Englisch, Spanisch, Deutsch, Italienisch und Portugiesisch werden erkannt.",
    "Das haben wir vorbereitet",
    "Vor dem Erstellen prüfen. Fehlende Informationen werden niemals erfunden.",
    "Wichtige Angaben fehlen: {count}. Sie können diese danach ergänzen.",
    "Name der Unterkunft",
    "Meine Unterkunft",
    "Gefundene Fotos",
    "Foto aus der Quelle",
    "Diese Fotos importieren: Ich habe die Nutzungsrechte.",
    "Quelle gespeichert",
    "Quelltext anzeigen",
    "Wird erstellt…",
    "Diese Unterkunft erstellen",
    "Hier bearbeitete Felder werden als manuell geprüft markiert.",
    "Eingeben: {label}",
  ],
  it: [
    "Lettura dell’alloggio",
    "Ricerca del nome",
    "Ricerca della descrizione",
    "Ricerca delle dotazioni",
    "Organizzazione delle informazioni",
    "Lettura del testo",
    "Suddivisione per tema",
    "Rilevamento delle informazioni incerte",
    "Preparazione della verifica",
    "Questo link Airbnb è una ricerca. Apri l’alloggio e copia il suo link.",
    "Il link sembra incompleto. Copialo dalla barra degli indirizzi.",
    "Prova un altro link",
    "Non abbiamo trovato informazioni sufficienti. Aggiungi testo o crea l’alloggio manualmente.",
    "I tuoi appunti, un messaggio WhatsApp, un’email, il testo dell’annuncio…",
    "Prova un esempio",
    "Sono riconosciuti francese, inglese, spagnolo, tedesco, italiano e portoghese.",
    "Ecco cosa abbiamo preparato",
    "Verifica prima di creare l’alloggio. Non inventiamo informazioni mancanti.",
    "Informazioni importanti da completare: {count}. Potrai aggiungerle dopo.",
    "Nome dell’alloggio",
    "Il mio alloggio",
    "Foto rilevate",
    "Foto dalla fonte",
    "Importa queste foto: ho il diritto di utilizzarle.",
    "Fonte conservata",
    "Vedi il testo originale",
    "Creazione…",
    "Crea questo alloggio",
    "I campi modificati qui sono verificati manualmente.",
    "Inserisci: {label}",
  ],
  pt: [
    "A ler o alojamento",
    "A procurar o nome",
    "A procurar a descrição",
    "A procurar equipamentos",
    "A organizar informações",
    "A ler o seu texto",
    "A ordenar por tema",
    "A detetar informações incertas",
    "A preparar a verificação",
    "Este link Airbnb é uma pesquisa. Abra o alojamento e copie o seu link.",
    "Este link parece incompleto. Copie-o da barra de endereços.",
    "Experimentar outro link",
    "Não encontrámos informações suficientes. Adicione texto ou crie o alojamento manualmente.",
    "As suas notas, uma mensagem WhatsApp, um email, o texto do anúncio…",
    "Experimentar um exemplo",
    "São reconhecidos francês, inglês, espanhol, alemão, italiano e português.",
    "Aqui está o que preparámos",
    "Verifique antes de criar o alojamento. Não inventamos informações em falta.",
    "Informações importantes em falta: {count}. Pode completá-las depois.",
    "Nome do alojamento",
    "O meu alojamento",
    "Fotos detetadas",
    "Foto da fonte",
    "Importar estas fotos: tenho autorização para as utilizar.",
    "Fonte preservada",
    "Ver texto original",
    "A criar…",
    "Criar este alojamento",
    "Os campos editados aqui são verificados manualmente.",
    "Introduza: {label}",
  ],
};
const labels: Record<Locale, readonly string[]> = {
  fr: FIELD_DEFS.map((field) => field.label),
  en: [
    "Description",
    "Address",
    "Arrival time",
    "Keys and access",
    "Parking",
    "Wi-Fi",
    "Capacity and bedrooms",
    "Amenities",
    "Kitchen",
    "Heating and air conditioning",
    "House rules",
    "Waste and recycling",
    "Pool / spa",
    "Local recommendations",
    "Available services",
    "Departure",
    "Contact",
    "Emergencies",
  ],
  es: [
    "Descripción",
    "Dirección",
    "Hora de llegada",
    "Llaves y acceso",
    "Aparcamiento",
    "Wi-Fi",
    "Capacidad y habitaciones",
    "Equipamiento",
    "Cocina",
    "Calefacción y aire acondicionado",
    "Normas de la casa",
    "Basura y reciclaje",
    "Piscina / spa",
    "Recomendaciones locales",
    "Servicios disponibles",
    "Salida",
    "Contacto",
    "Emergencias",
  ],
  de: [
    "Beschreibung",
    "Adresse",
    "Ankunftszeit",
    "Schlüssel und Zugang",
    "Parken",
    "WLAN",
    "Kapazität und Schlafzimmer",
    "Ausstattung",
    "Küche",
    "Heizung und Klimaanlage",
    "Hausregeln",
    "Abfall und Recycling",
    "Pool / Spa",
    "Lokale Empfehlungen",
    "Verfügbare Services",
    "Abreise",
    "Kontakt",
    "Notfälle",
  ],
  it: [
    "Descrizione",
    "Indirizzo",
    "Orario di arrivo",
    "Chiavi e accesso",
    "Parcheggio",
    "Wi-Fi",
    "Capienza e camere",
    "Dotazioni",
    "Cucina",
    "Riscaldamento e climatizzazione",
    "Regole della casa",
    "Rifiuti e riciclaggio",
    "Piscina / spa",
    "Consigli locali",
    "Servizi disponibili",
    "Partenza",
    "Contatto",
    "Emergenze",
  ],
  pt: [
    "Descrição",
    "Morada",
    "Hora de chegada",
    "Chaves e acesso",
    "Estacionamento",
    "Wi-Fi",
    "Capacidade e quartos",
    "Equipamentos",
    "Cozinha",
    "Aquecimento e ar condicionado",
    "Regras da casa",
    "Lixo e reciclagem",
    "Piscina / spa",
    "Recomendações locais",
    "Serviços disponíveis",
    "Partida",
    "Contacto",
    "Emergências",
  ],
};
export function addImportCopy(translations: Record<Locale, Record<string, string>>) {
  for (const locale of Object.keys(copy) as Locale[]) {
    keys.forEach((key, index) => {
      translations[locale][`importFlow.${key}`] = copy[locale][index]!;
    });
    FIELD_DEFS.forEach((field, index) => {
      translations[locale][`field.${field.key}`] = labels[locale][index]!;
    });
  }
}
