import type { Locale } from "./i18n";
const keys = [
  "subscription",
  "services",
  "notConfigured",
  "setup",
  "manage",
  "connect",
  "refresh",
  "error",
  "test",
  "paid",
  "pending",
  "refunded",
  "refund",
  "paymentLink",
  "copy",
  "confirmation",
  "pay",
  "unavailable",
  "success",
  "amount",
  "receipts",
  "active",
  "trial",
  "inactive",
  "failed",
  "partialRefund",
] as const;
const values: Record<Locale, string[]> = {
  fr: [
    "Abonnement HostBuddy",
    "Paiements voyageurs",
    "Les paiements ne sont pas encore activés.",
    "Choisir cette offre",
    "Carte et factures",
    "Activer les paiements",
    "Actualiser",
    "Cette action est indisponible. Réessayez plus tard.",
    "Mode test — aucun paiement réel",
    "Payé",
    "En attente de paiement",
    "Remboursé",
    "Rembourser",
    "Créer un lien de paiement",
    "Copier le lien",
    "Le service est confirmé par votre hôte. Le paiement se fait sur la page sécurisée Stripe.",
    "Payer en toute sécurité",
    "Ce lien n’est plus disponible.",
    "Paiement reçu",
    "Montant",
    "Encaissements",
    "Abonnement actif",
    "Période d’essai",
    "Abonnement inactif",
    "Paiement non abouti",
    "Partiellement remboursé",
  ],
  en: [
    "HostBuddy subscription",
    "Guest payments",
    "Payments are not activated yet.",
    "Choose this plan",
    "Card and invoices",
    "Activate payments",
    "Refresh",
    "This action is unavailable. Try again later.",
    "Test mode — no real payment",
    "Paid",
    "Awaiting payment",
    "Refunded",
    "Refund",
    "Create payment link",
    "Copy link",
    "Your host has confirmed the service. Payment takes place on Stripe’s secure page.",
    "Pay securely",
    "This link is no longer available.",
    "Payment received",
    "Amount",
    "Receipts",
    "Active subscription",
    "Trial period",
    "Inactive subscription",
    "Payment unsuccessful",
    "Partially refunded",
  ],
  es: [
    "Suscripción HostBuddy",
    "Pagos de viajeros",
    "Los pagos aún no están activados.",
    "Elegir esta oferta",
    "Tarjeta y facturas",
    "Activar pagos",
    "Actualizar",
    "Esta acción no está disponible. Inténtalo más tarde.",
    "Modo de prueba — sin pago real",
    "Pagado",
    "Pendiente de pago",
    "Reembolsado",
    "Reembolsar",
    "Crear enlace de pago",
    "Copiar enlace",
    "Tu anfitrión ha confirmado el servicio. El pago se realiza en la página segura de Stripe.",
    "Pagar de forma segura",
    "Este enlace ya no está disponible.",
    "Pago recibido",
    "Importe",
    "Cobros",
    "Suscripción activa",
    "Periodo de prueba",
    "Suscripción inactiva",
    "Pago no completado",
    "Reembolso parcial",
  ],
  de: [
    "HostBuddy-Abonnement",
    "Gastzahlungen",
    "Zahlungen sind noch nicht aktiviert.",
    "Dieses Angebot wählen",
    "Karte und Rechnungen",
    "Zahlungen aktivieren",
    "Aktualisieren",
    "Diese Aktion ist nicht verfügbar. Bitte später erneut versuchen.",
    "Testmodus — keine echte Zahlung",
    "Bezahlt",
    "Zahlung ausstehend",
    "Erstattet",
    "Erstatten",
    "Zahlungslink erstellen",
    "Link kopieren",
    "Ihr Gastgeber hat den Service bestätigt. Die Zahlung erfolgt auf der sicheren Stripe-Seite.",
    "Sicher bezahlen",
    "Dieser Link ist nicht mehr verfügbar.",
    "Zahlung erhalten",
    "Betrag",
    "Einnahmen",
    "Aktives Abonnement",
    "Testzeitraum",
    "Inaktives Abonnement",
    "Zahlung nicht abgeschlossen",
    "Teilweise erstattet",
  ],
  it: [
    "Abbonamento HostBuddy",
    "Pagamenti ospiti",
    "I pagamenti non sono ancora attivi.",
    "Scegli questa offerta",
    "Carta e fatture",
    "Attiva i pagamenti",
    "Aggiorna",
    "Questa azione non è disponibile. Riprova più tardi.",
    "Modalità test — nessun pagamento reale",
    "Pagato",
    "In attesa di pagamento",
    "Rimborsato",
    "Rimborsa",
    "Crea link di pagamento",
    "Copia link",
    "Il tuo host ha confermato il servizio. Il pagamento avviene sulla pagina sicura di Stripe.",
    "Paga in sicurezza",
    "Questo link non è più disponibile.",
    "Pagamento ricevuto",
    "Importo",
    "Incassi",
    "Abbonamento attivo",
    "Periodo di prova",
    "Abbonamento inattivo",
    "Pagamento non riuscito",
    "Rimborso parziale",
  ],
  pt: [
    "Assinatura HostBuddy",
    "Pagamentos dos hóspedes",
    "Os pagamentos ainda não estão ativos.",
    "Escolher esta oferta",
    "Cartão e faturas",
    "Ativar pagamentos",
    "Atualizar",
    "Esta ação não está disponível. Tente mais tarde.",
    "Modo de teste — sem pagamento real",
    "Pago",
    "Aguardando pagamento",
    "Reembolsado",
    "Reembolsar",
    "Criar link de pagamento",
    "Copiar link",
    "O anfitrião confirmou o serviço. O pagamento é feito na página segura do Stripe.",
    "Pagar com segurança",
    "Este link já não está disponível.",
    "Pagamento recebido",
    "Valor",
    "Recebimentos",
    "Assinatura ativa",
    "Período de teste",
    "Assinatura inativa",
    "Pagamento não concluído",
    "Reembolso parcial",
  ],
};
export function addPaymentCopy(copy: Record<Locale, Record<string, string>>) {
  for (const locale of Object.keys(values) as Locale[])
    keys.forEach((key, index) => {
      copy[locale][`payments.${key}`] = values[locale][index]!;
    });
}
