import type { Locale } from "./i18n";
const keys = [
  "subscription",
  "services",
  "notConfigured",
  "setup",
  "manage",
  "connect",
  "refresh",
  "error",
  "test",
  "paid",
  "pending",
  "refunded",
  "refund",
  "paymentLink",
  "copy",
  "confirmation",
  "pay",
  "unavailable",
  "success",
  "amount",
  "receipts",
  "active",
  "trial",
  "inactive",
  "failed",
  "partialRefund",
  "free",
  "freeNote",
  "counter",
  "feeTerms",
  "feeAccept",
  "feeAmount",
  "feeRefundNote",
  "syncPending",
  "syncNote",
  "servicePhoto",
  "noPhoto",
] as const;
const values: Record<Locale, string[]> = {
  fr: [
    "Abonnement HostBuddy",
    "Paiements voyageurs",
    "Les paiements ne sont pas encore activés.",
    "Choisir cette offre",
    "Carte et factures",
    "Activer les paiements",
    "Actualiser",
    "Cette action est indisponible. Réessayez plus tard.",
    "Mode test — aucun paiement réel",
    "Payé",
    "En attente de paiement",
    "Remboursé",
    "Rembourser",
    "Créer un lien de paiement",
    "Copier le lien",
    "Le service est confirmé par votre hôte. Le paiement se fait sur la page sécurisée Stripe.",
    "Payer en toute sécurité",
    "Ce lien n’est plus disponible.",
    "Paiement reçu",
    "Montant",
    "Encaissements",
    "Abonnement actif",
    "Période d’essai",
    "Abonnement inactif",
    "Paiement non abouti",
    "Partiellement remboursé",
    "Free · 1 logement · 0 € / mois",
    "Votre premier logement reste gratuit, sans abonnement.",
    "{count} logement(s) · {amount} / mois",
    "HostBuddy prélève 2 % sur les services payés, en plus des frais Stripe. Le montant est arrondi au centime par commande.",
    "J’accepte la commission HostBuddy de 2 % sur mes ventes de services.",
    "Commission HostBuddy : {amount}",
    "En cas de remboursement, la commission HostBuddy est remboursée proportionnellement. Les frais Stripe sont distincts.",
    "La synchronisation de l’abonnement est en attente. Réessayez ou actualisez.",
    "Brouillons et guides publiés comptés ; logements archivés exclus. Les changements sont calculés au prorata par Stripe.",
    "Photo du service",
    "Sans photo",
  ],
  en: [
    "HostBuddy subscription",
    "Guest payments",
    "Payments are not activated yet.",
    "Choose this plan",
    "Card and invoices",
    "Activate payments",
    "Refresh",
    "This action is unavailable. Try again later.",
    "Test mode — no real payment",
    "Paid",
    "Awaiting payment",
    "Refunded",
    "Refund",
    "Create payment link",
    "Copy link",
    "Your host has confirmed the service. Payment takes place on Stripe’s secure page.",
    "Pay securely",
    "This link is no longer available.",
    "Payment received",
    "Amount",
    "Receipts",
    "Active subscription",
    "Trial period",
    "Inactive subscription",
    "Payment unsuccessful",
    "Partially refunded",
    "Free · 1 property · €0 / month",
    "Your first property stays free, without a subscription.",
    "{count} property/properties · {amount} / month",
    "HostBuddy collects 2% on paid services, in addition to Stripe fees. Rounded to the nearest cent per order.",
    "I accept the 2% HostBuddy fee on my service sales.",
    "HostBuddy fee: {amount}",
    "For refunds, the HostBuddy fee is refunded proportionally. Stripe fees are separate.",
    "Subscription sync is pending. Retry or refresh.",
    "Draft and published properties count; archived properties are excluded. Stripe prorates changes.",
    "Service photo",
    "No photo",
  ],
  es: [
    "Suscripción HostBuddy",
    "Pagos de viajeros",
    "Los pagos aún no están activados.",
    "Elegir esta oferta",
    "Tarjeta y facturas",
    "Activar pagos",
    "Actualizar",
    "Esta acción no está disponible. Inténtalo más tarde.",
    "Modo de prueba — sin pago real",
    "Pagado",
    "Pendiente de pago",
    "Reembolsado",
    "Reembolsar",
    "Crear enlace de pago",
    "Copiar enlace",
    "Tu anfitrión ha confirmado el servicio. El pago se realiza en la página segura de Stripe.",
    "Pagar de forma segura",
    "Este enlace ya no está disponible.",
    "Pago recibido",
    "Importe",
    "Cobros",
    "Suscripción activa",
    "Periodo de prueba",
    "Suscripción inactiva",
    "Pago no completado",
    "Reembolso parcial",
    "Free · 1 alojamiento · 0 € / mes",
    "Tu primer alojamiento sigue siendo gratuito, sin suscripción.",
    "{count} alojamiento(s) · {amount} / mes",
    "HostBuddy cobra un 2 % por los servicios pagados, además de las tarifas de Stripe. Se redondea al céntimo por pedido.",
    "Acepto la comisión HostBuddy del 2 % sobre mis ventas de servicios.",
    "Comisión HostBuddy: {amount}",
    "En los reembolsos, la comisión HostBuddy se devuelve proporcionalmente. Las tarifas de Stripe son independientes.",
    "La sincronización está pendiente. Reintenta o actualiza.",
    "Se cuentan borradores y guías publicadas; se excluyen alojamientos archivados. Stripe prorratea los cambios.",
    "Foto del servicio",
    "Sin foto",
  ],
  de: [
    "HostBuddy-Abonnement",
    "Gastzahlungen",
    "Zahlungen sind noch nicht aktiviert.",
    "Dieses Angebot wählen",
    "Karte und Rechnungen",
    "Zahlungen aktivieren",
    "Aktualisieren",
    "Diese Aktion ist nicht verfügbar. Bitte später erneut versuchen.",
    "Testmodus — keine echte Zahlung",
    "Bezahlt",
    "Zahlung ausstehend",
    "Erstattet",
    "Erstatten",
    "Zahlungslink erstellen",
    "Link kopieren",
    "Ihr Gastgeber hat den Service bestätigt. Die Zahlung erfolgt auf der sicheren Stripe-Seite.",
    "Sicher bezahlen",
    "Dieser Link ist nicht mehr verfügbar.",
    "Zahlung erhalten",
    "Betrag",
    "Einnahmen",
    "Aktives Abonnement",
    "Testzeitraum",
    "Inaktives Abonnement",
    "Zahlung nicht abgeschlossen",
    "Teilweise erstattet",
    "Free · 1 Unterkunft · 0 € / Monat",
    "Ihre erste Unterkunft bleibt kostenlos, ohne Abonnement.",
    "{count} Unterkunft/Unterkünfte · {amount} / Monat",
    "HostBuddy erhebt 2 % auf bezahlte Services, zusätzlich zu Stripe-Gebühren. Pro Bestellung auf Cent gerundet.",
    "Ich akzeptiere 2 % HostBuddy-Gebühr auf meine Serviceverkäufe.",
    "HostBuddy-Gebühr: {amount}",
    "Bei Erstattungen wird die HostBuddy-Gebühr anteilig erstattet. Stripe-Gebühren sind separat.",
    "Abonnementsynchronisierung ausstehend. Erneut versuchen oder aktualisieren.",
    "Entwürfe und veröffentlichte Unterkünfte zählen; archivierte nicht. Stripe berechnet Änderungen anteilig.",
    "Servicefoto",
    "Ohne Foto",
  ],
  it: [
    "Abbonamento HostBuddy",
    "Pagamenti ospiti",
    "I pagamenti non sono ancora attivi.",
    "Scegli questa offerta",
    "Carta e fatture",
    "Attiva i pagamenti",
    "Aggiorna",
    "Questa azione non è disponibile. Riprova più tardi.",
    "Modalità test — nessun pagamento reale",
    "Pagato",
    "In attesa di pagamento",
    "Rimborsato",
    "Rimborsa",
    "Crea link di pagamento",
    "Copia link",
    "Il tuo host ha confermato il servizio. Il pagamento avviene sulla pagina sicura di Stripe.",
    "Paga in sicurezza",
    "Questo link non è più disponibile.",
    "Pagamento ricevuto",
    "Importo",
    "Incassi",
    "Abbonamento attivo",
    "Periodo di prova",
    "Abbonamento inattivo",
    "Pagamento non riuscito",
    "Rimborso parziale",
    "Free · 1 alloggio · 0 € / mese",
    "Il primo alloggio resta gratuito, senza abbonamento.",
    "{count} alloggio/i · {amount} / mese",
    "HostBuddy trattiene il 2 % sui servizi pagati, oltre alle commissioni Stripe. Arrotondato al centesimo per ordine.",
    "Accetto la commissione HostBuddy del 2 % sulle mie vendite di servizi.",
    "Commissione HostBuddy: {amount}",
    "In caso di rimborso la commissione HostBuddy viene rimborsata proporzionalmente. Le commissioni Stripe sono separate.",
    "Sincronizzazione in attesa. Riprova o aggiorna.",
    "Sono conteggiati bozze e guide pubblicate; gli alloggi archiviati sono esclusi. Stripe calcola le variazioni pro rata.",
    "Foto del servizio",
    "Senza foto",
  ],
  pt: [
    "Assinatura HostBuddy",
    "Pagamentos dos hóspedes",
    "Os pagamentos ainda não estão ativos.",
    "Escolher esta oferta",
    "Cartão e faturas",
    "Ativar pagamentos",
    "Atualizar",
    "Esta ação não está disponível. Tente mais tarde.",
    "Modo de teste — sem pagamento real",
    "Pago",
    "Aguardando pagamento",
    "Reembolsado",
    "Reembolsar",
    "Criar link de pagamento",
    "Copiar link",
    "O anfitrião confirmou o serviço. O pagamento é feito na página segura do Stripe.",
    "Pagar com segurança",
    "Este link já não está disponível.",
    "Pagamento recebido",
    "Valor",
    "Recebimentos",
    "Assinatura ativa",
    "Período de teste",
    "Assinatura inativa",
    "Pagamento não concluído",
    "Reembolso parcial",
    "Free · 1 alojamento · 0 € / mês",
    "O primeiro alojamento mantém-se gratuito, sem assinatura.",
    "{count} alojamento(s) · {amount} / mês",
    "HostBuddy cobra 2 % nos serviços pagos, além das taxas Stripe. Arredondado ao cêntimo por encomenda.",
    "Aceito a comissão HostBuddy de 2 % nas minhas vendas de serviços.",
    "Comissão HostBuddy: {amount}",
    "Nos reembolsos, a comissão HostBuddy é devolvida proporcionalmente. As taxas Stripe são separadas.",
    "Sincronização pendente. Tente novamente ou atualize.",
    "Contam rascunhos e guias publicadas; alojamentos arquivados ficam excluídos. Stripe calcula alterações proporcionalmente.",
    "Fotografia do serviço",
    "Sem fotografia",
  ],
};
export function addPaymentCopy(copy: Record<Locale, Record<string, string>>) {
  for (const locale of Object.keys(connectCopy) as Locale[])
    connectKeys.forEach((key, index) => {
      copy[locale][`payments.connect.${key}`] = connectCopy[locale][index]!;
    });
  for (const locale of Object.keys(values) as Locale[])
    keys.forEach((key, index) => {
      copy[locale][`payments.${key}`] = values[locale][index]!;
    });
}

const connectKeys = [
  "start",
  "resume",
  "notConnected",
  "incomplete",
  "verification",
  "restricted",
  "ready",
  "payoutsPending",
  "returned",
  "remaining",
  "required.business",
  "required.identity",
  "required.address",
  "required.contact",
  "required.bank",
  "required.terms",
  "required.other",
] as const;
const connectCopy: Record<Locale, string[]> = {
  fr: [
    "Connecter Stripe",
    "Compléter mon compte Stripe",
    "Aucun compte Stripe connecté.",
    "Compte connecté : des informations restent à compléter.",
    "Stripe vérifie les informations fournies.",
    "Stripe n’autorise pas encore les encaissements. Consultez votre compte Stripe.",
    "Encaissements et virements autorisés par Stripe.",
    "Les encaissements sont autorisés ; les virements bancaires restent à activer dans Stripe.",
    "Retour de Stripe : le statut ci-dessus est vérifié auprès de Stripe.",
    "À compléter dans Stripe :",
    "Activité et informations de l’entreprise",
    "Identité du représentant et justificatifs",
    "Adresse",
    "Coordonnées de contact",
    "Compte bancaire pour les virements",
    "Conditions Stripe à examiner par le titulaire du compte",
    "Autres informations ou corrections demandées par Stripe",
  ],
  en: [
    "Connect Stripe",
    "Complete my Stripe account",
    "No Stripe account connected.",
    "Account connected: information is still required.",
    "Stripe is verifying the submitted information.",
    "Stripe has not authorized payments yet. Check your Stripe account.",
    "Payments and payouts authorized by Stripe.",
    "Payments are authorized; bank payouts still need activation in Stripe.",
    "Returned from Stripe: the status above is checked with Stripe.",
    "Complete in Stripe:",
    "Business activity and details",
    "Representative identity and supporting documents",
    "Address",
    "Contact details",
    "Bank account for payouts",
    "Stripe terms for the account holder to review",
    "Other information or corrections requested by Stripe",
  ],
  es: [
    "Conectar Stripe",
    "Completar mi cuenta Stripe",
    "Ninguna cuenta Stripe conectada.",
    "Cuenta conectada: falta información.",
    "Stripe está verificando la información enviada.",
    "Stripe aún no autoriza los cobros. Consulte su cuenta Stripe.",
    "Cobros y transferencias autorizados por Stripe.",
    "Cobros autorizados; falta activar las transferencias bancarias en Stripe.",
    "Regreso de Stripe: el estado anterior se verifica con Stripe.",
    "Completar en Stripe:",
    "Actividad y datos de la empresa",
    "Identidad del representante y documentos",
    "Dirección",
    "Datos de contacto",
    "Cuenta bancaria para transferencias",
    "Condiciones Stripe para que las revise el titular",
    "Otra información o correcciones solicitadas por Stripe",
  ],
  de: [
    "Stripe verbinden",
    "Mein Stripe-Konto vervollständigen",
    "Kein Stripe-Konto verbunden.",
    "Konto verbunden: Angaben fehlen noch.",
    "Stripe überprüft die übermittelten Angaben.",
    "Stripe erlaubt noch keine Zahlungen. Prüfen Sie Ihr Stripe-Konto.",
    "Zahlungen und Auszahlungen von Stripe freigegeben.",
    "Zahlungen freigegeben; Bankauszahlungen müssen noch in Stripe aktiviert werden.",
    "Rückkehr von Stripe: Der obige Status wird bei Stripe geprüft.",
    "In Stripe ergänzen:",
    "Geschäftstätigkeit und Unternehmensangaben",
    "Identität der Vertretung und Nachweise",
    "Adresse",
    "Kontaktdaten",
    "Bankkonto für Auszahlungen",
    "Stripe-Bedingungen zur Prüfung durch den Kontoinhaber",
    "Weitere Angaben oder Korrekturen, die Stripe anfordert",
  ],
  it: [
    "Collega Stripe",
    "Completa il mio account Stripe",
    "Nessun account Stripe collegato.",
    "Account collegato: mancano alcune informazioni.",
    "Stripe sta verificando le informazioni inviate.",
    "Stripe non autorizza ancora gli incassi. Consulta il tuo account Stripe.",
    "Incassi e bonifici autorizzati da Stripe.",
    "Incassi autorizzati; i bonifici bancari devono ancora essere attivati in Stripe.",
    "Ritorno da Stripe: lo stato sopra è verificato con Stripe.",
    "Da completare in Stripe:",
    "Attività e dati aziendali",
    "Identità del rappresentante e documenti",
    "Indirizzo",
    "Recapiti",
    "Conto bancario per i bonifici",
    "Condizioni Stripe da esaminare dal titolare",
    "Altre informazioni o correzioni richieste da Stripe",
  ],
  pt: [
    "Ligar Stripe",
    "Completar a minha conta Stripe",
    "Nenhuma conta Stripe ligada.",
    "Conta ligada: faltam informações.",
    "Stripe está a verificar as informações enviadas.",
    "Stripe ainda não autoriza cobranças. Consulte a sua conta Stripe.",
    "Cobranças e transferências autorizadas por Stripe.",
    "Cobranças autorizadas; falta ativar as transferências bancárias em Stripe.",
    "Regresso de Stripe: o estado acima é verificado junto da Stripe.",
    "Completar em Stripe:",
    "Atividade e dados da empresa",
    "Identidade do representante e documentos",
    "Morada",
    "Dados de contacto",
    "Conta bancária para transferências",
    "Condições Stripe para revisão pelo titular",
    "Outras informações ou correções solicitadas pela Stripe",
  ],
};
