import type { Locale } from "./i18n";
const keys = [
  "title",
  "description",
  "connect",
  "clientId",
  "clientSecret",
  "credentials",
  "notConfigured",
  "import",
  "selected",
  "loadMore",
  "connected",
  "notConnected",
  "error",
  "oneTime",
  "drafts",
  "disconnect",
  "review",
  "photos",
] as const;
const values: Record<Locale, string[]> = {
  fr: [
    "Importer depuis Guesty",
    "Sélectionnez vos logements. HostBuddy crée des brouillons à vérifier.",
    "Se connecter à Guesty",
    "Client ID",
    "Client Secret",
    "Utilisez les identifiants Open API de votre compte Guesty.",
    "Cette connexion nécessite encore une configuration serveur.",
    "Importer la sélection",
    "sélectionné(s)",
    "Voir les suivants",
    "Connexion vérifiée",
    "Non connecté",
    "La connexion ou l’import a échoué. Vérifiez vos accès ou réessayez plus tard.",
    "Import unique : vos modifications ne sont jamais écrasées automatiquement.",
    "Brouillons créés",
    "Déconnecter Guesty",
    "Vérifier le logement",
    "Les photos du PMS ne sont pas encore transférées automatiquement. Ajoutez vos photos dans Médias.",
  ],
  en: [
    "Import from Guesty",
    "Select properties. HostBuddy creates drafts for review.",
    "Connect to Guesty",
    "Client ID",
    "Client Secret",
    "Use the Open API credentials from your Guesty account.",
    "This connection still needs server configuration.",
    "Import selection",
    "selected",
    "Load more",
    "Connection verified",
    "Not connected",
    "Connection or import failed. Check access or try again later.",
    "One-time import: your edits are never overwritten automatically.",
    "Drafts created",
    "Disconnect Guesty",
    "Review property",
    "PMS photos are not transferred automatically yet. Add photos in Media.",
  ],
  es: [
    "Importar desde Guesty",
    "Selecciona alojamientos. HostBuddy crea borradores para revisar.",
    "Conectar Guesty",
    "Client ID",
    "Client Secret",
    "Usa las credenciales Open API de tu cuenta Guesty.",
    "Esta conexión necesita configuración del servidor.",
    "Importar selección",
    "seleccionados",
    "Ver más",
    "Conexión verificada",
    "No conectado",
    "La conexión o importación falló. Comprueba el acceso o inténtalo más tarde.",
    "Importación única: tus cambios nunca se sobrescriben automáticamente.",
    "Borradores creados",
    "Desconectar Guesty",
    "Revisar alojamiento",
    "Las fotos del PMS aún no se transfieren automáticamente. Añade fotos en Medios.",
  ],
  de: [
    "Aus Guesty importieren",
    "Unterkünfte auswählen. HostBuddy erstellt Entwürfe zur Prüfung.",
    "Mit Guesty verbinden",
    "Client ID",
    "Client Secret",
    "Open-API-Zugangsdaten Ihres Guesty-Kontos verwenden.",
    "Diese Verbindung benötigt noch eine Serverkonfiguration.",
    "Auswahl importieren",
    "ausgewählt",
    "Mehr anzeigen",
    "Verbindung geprüft",
    "Nicht verbunden",
    "Verbindung oder Import fehlgeschlagen. Zugang prüfen oder später erneut versuchen.",
    "Einmaliger Import: Ihre Änderungen werden niemals automatisch überschrieben.",
    "Entwürfe erstellt",
    "Guesty trennen",
    "Unterkunft prüfen",
    "PMS-Fotos werden noch nicht automatisch übertragen. Fotos unter Medien hinzufügen.",
  ],
  it: [
    "Importa da Guesty",
    "Seleziona alloggi. HostBuddy crea bozze da verificare.",
    "Connetti Guesty",
    "Client ID",
    "Client Secret",
    "Usa le credenziali Open API del tuo account Guesty.",
    "La connessione richiede ancora una configurazione del server.",
    "Importa selezione",
    "selezionati",
    "Mostra altri",
    "Connessione verificata",
    "Non connesso",
    "Connessione o importazione non riuscita. Verifica gli accessi o riprova più tardi.",
    "Importazione unica: le tue modifiche non vengono mai sovrascritte automaticamente.",
    "Bozze create",
    "Disconnetti Guesty",
    "Verifica alloggio",
    "Le foto del PMS non vengono ancora trasferite automaticamente. Aggiungi foto in Media.",
  ],
  pt: [
    "Importar do Guesty",
    "Selecione alojamentos. HostBuddy cria rascunhos para verificar.",
    "Ligar ao Guesty",
    "Client ID",
    "Client Secret",
    "Use as credenciais Open API da sua conta Guesty.",
    "Esta ligação ainda requer configuração do servidor.",
    "Importar seleção",
    "selecionados",
    "Ver mais",
    "Ligação verificada",
    "Não ligado",
    "Falha na ligação ou importação. Verifique o acesso ou tente mais tarde.",
    "Importação única: as suas alterações nunca são substituídas automaticamente.",
    "Rascunhos criados",
    "Desligar Guesty",
    "Verificar alojamento",
    "As fotos do PMS ainda não são transferidas automaticamente. Adicione fotos em Multimédia.",
  ],
};
export function addProviderCopy(copy: Record<Locale, Record<string, string>>) {
  for (const locale of Object.keys(values) as Locale[])
    keys.forEach((key, index) => {
      copy[locale][`provider.${key}`] = values[locale][index]!;
    });
}
