import type { Locale } from "./i18n";
const keys = [
  "manager.searchProperties",
  "manager.noResults",
  "auth.forgot",
  "auth.resetTitle",
  "auth.resetHelp",
  "auth.sendReset",
  "auth.resetSent",
  "auth.newPassword",
  "auth.updatePassword",
  "auth.updatedPassword",
  "auth.invalidEmail",
  "auth.shortPassword",
  "auth.firstRequired",
  "auth.checkFields",
  "auth.existingError",
  "auth.invalidLogin",
  "auth.confirmEmail",
  "auth.weakPassword",
  "auth.failed",
  "auth.googleFailed",
  "auth.recoveryExpired",
  "offline.copy",
  "offline.savedGuides",
  "offline.myCopies",
  "offline.online",
  "offline.available",
  "offline.delete",
  "offline.noCopy",
  "offline.unavailable",
  "offline.requiresNetwork",
] as const;
const copy: Record<Locale, readonly string[]> = {
  fr: [
    "Rechercher un logement",
    "Aucun logement trouvé",
    "Mot de passe oublié ?",
    "Réinitialiser le mot de passe",
    "Recevez un lien sécurisé par e-mail.",
    "Envoyer le lien",
    "Si un compte correspond à cette adresse, un lien vous sera envoyé.",
    "Nouveau mot de passe",
    "Enregistrer le mot de passe",
    "Mot de passe mis à jour.",
    "Cette adresse e-mail ne semble pas correcte.",
    "Utilisez au moins 8 caractères.",
    "Indiquez votre prénom.",
    "Vérifiez vos informations.",
    "Un compte existe déjà avec cet e-mail. Connectez-vous.",
    "E-mail ou mot de passe incorrect.",
    "Confirmez votre adresse avec le lien reçu par e-mail.",
    "Choisissez un mot de passe plus fort.",
    "La connexion a échoué. Réessayez.",
    "La connexion Google n’a pas abouti. Réessayez ou utilisez votre e-mail.",
    "Ce lien a expiré. Demandez un nouveau lien.",
    "Copie enregistrée · lecture sans réseau",
    "Guides enregistrés",
    "Mes copies",
    "Version en ligne",
    "Disponibles sur cet appareil. Une mise à jour nécessite une connexion.",
    "Supprimer la copie locale",
    "Ce guide n’a pas été enregistré sur cet appareil.",
    "Le guide enregistré est indisponible.",
    "Une connexion est nécessaire pour envoyer une demande, un message ou un retour. Rien n’a été envoyé.",
  ],
  en: [
    "Search properties",
    "No properties found",
    "Forgot password?",
    "Reset your password",
    "Receive a secure link by email.",
    "Send reset link",
    "If an account matches this address, a reset link will be sent.",
    "New password",
    "Save password",
    "Password updated.",
    "Enter a valid email address.",
    "Use at least 8 characters.",
    "Enter your first name.",
    "Check your details.",
    "An account already exists with this email. Please sign in.",
    "Incorrect email or password.",
    "Confirm your email using the link you received.",
    "Choose a stronger password.",
    "Sign-in failed. Please try again.",
    "Google sign-in failed. Try again or use your email.",
    "This link has expired. Request a new link.",
    "Saved copy · offline reading",
    "Saved guides",
    "My copies",
    "Online version",
    "Available on this device. Updates require a connection.",
    "Delete local copy",
    "This guide has not been saved on this device.",
    "The saved guide is unavailable.",
    "A connection is required to send a request, message or feedback. Nothing has been sent.",
  ],
  es: [
    "Buscar alojamientos",
    "No se encontraron alojamientos",
    "¿Olvidaste tu contraseña?",
    "Restablecer contraseña",
    "Recibe un enlace seguro por correo.",
    "Enviar enlace",
    "Si existe una cuenta con esta dirección, recibirás un enlace.",
    "Nueva contraseña",
    "Guardar contraseña",
    "Contraseña actualizada.",
    "Introduce un correo válido.",
    "Usa al menos 8 caracteres.",
    "Introduce tu nombre.",
    "Revisa tus datos.",
    "Ya existe una cuenta con este correo. Inicia sesión.",
    "Correo o contraseña incorrectos.",
    "Confirma tu correo mediante el enlace recibido.",
    "Elige una contraseña más segura.",
    "No se pudo iniciar sesión. Inténtalo de nuevo.",
    "No se pudo iniciar sesión con Google. Reintenta o usa tu correo.",
    "El enlace ha caducado. Solicita otro.",
    "Copia guardada · lectura sin conexión",
    "Guías guardadas",
    "Mis copias",
    "Versión en línea",
    "Disponibles en este dispositivo. Las actualizaciones necesitan conexión.",
    "Eliminar copia local",
    "Esta guía no está guardada en este dispositivo.",
    "La guía guardada no está disponible.",
    "Se necesita conexión para enviar una solicitud, mensaje o comentario. No se ha enviado nada.",
  ],
  de: [
    "Unterkünfte suchen",
    "Keine Unterkünfte gefunden",
    "Passwort vergessen?",
    "Passwort zurücksetzen",
    "Erhalte einen sicheren Link per E-Mail.",
    "Link senden",
    "Wenn ein Konto mit dieser Adresse existiert, erhältst du einen Link.",
    "Neues Passwort",
    "Passwort speichern",
    "Passwort aktualisiert.",
    "Gib eine gültige E-Mail-Adresse ein.",
    "Verwende mindestens 8 Zeichen.",
    "Gib deinen Vornamen ein.",
    "Prüfe deine Angaben.",
    "Für diese E-Mail besteht bereits ein Konto. Melde dich an.",
    "E-Mail oder Passwort falsch.",
    "Bestätige deine E-Mail über den erhaltenen Link.",
    "Wähle ein stärkeres Passwort.",
    "Anmeldung fehlgeschlagen. Versuche es erneut.",
    "Google-Anmeldung fehlgeschlagen. Versuche es erneut oder nutze deine E-Mail.",
    "Dieser Link ist abgelaufen. Fordere einen neuen an.",
    "Gespeicherte Kopie · offline lesen",
    "Gespeicherte Reiseführer",
    "Meine Kopien",
    "Online-Version",
    "Auf diesem Gerät verfügbar. Aktualisierungen benötigen eine Verbindung.",
    "Lokale Kopie löschen",
    "Dieser Reiseführer wurde nicht auf diesem Gerät gespeichert.",
    "Der gespeicherte Reiseführer ist nicht verfügbar.",
    "Zum Senden von Anfragen, Nachrichten oder Feedback ist eine Verbindung nötig. Es wurde nichts gesendet.",
  ],
  it: [
    "Cerca alloggi",
    "Nessun alloggio trovato",
    "Password dimenticata?",
    "Reimposta password",
    "Ricevi un link sicuro via e-mail.",
    "Invia link",
    "Se esiste un account con questo indirizzo, riceverai un link.",
    "Nuova password",
    "Salva password",
    "Password aggiornata.",
    "Inserisci un indirizzo e-mail valido.",
    "Usa almeno 8 caratteri.",
    "Inserisci il tuo nome.",
    "Controlla i dati.",
    "Esiste già un account con questa e-mail. Accedi.",
    "E-mail o password errata.",
    "Conferma la tua e-mail con il link ricevuto.",
    "Scegli una password più sicura.",
    "Accesso non riuscito. Riprova.",
    "Accesso Google non riuscito. Riprova o usa la tua e-mail.",
    "Questo link è scaduto. Richiedine un altro.",
    "Copia salvata · lettura offline",
    "Guide salvate",
    "Le mie copie",
    "Versione online",
    "Disponibili su questo dispositivo. Gli aggiornamenti richiedono una connessione.",
    "Elimina copia locale",
    "Questa guida non è stata salvata su questo dispositivo.",
    "La guida salvata non è disponibile.",
    "Serve una connessione per inviare una richiesta, un messaggio o un commento. Nulla è stato inviato.",
  ],
  pt: [
    "Pesquisar alojamentos",
    "Nenhum alojamento encontrado",
    "Esqueceu a palavra-passe?",
    "Redefinir palavra-passe",
    "Receba um link seguro por e-mail.",
    "Enviar link",
    "Se existir uma conta com este endereço, receberá um link.",
    "Nova palavra-passe",
    "Guardar palavra-passe",
    "Palavra-passe atualizada.",
    "Introduza um e-mail válido.",
    "Use pelo menos 8 caracteres.",
    "Introduza o seu nome.",
    "Verifique os seus dados.",
    "Já existe uma conta com este e-mail. Inicie sessão.",
    "E-mail ou palavra-passe incorretos.",
    "Confirme o e-mail através do link recebido.",
    "Escolha uma palavra-passe mais forte.",
    "Não foi possível iniciar sessão. Tente novamente.",
    "O acesso Google falhou. Tente novamente ou use o e-mail.",
    "Este link expirou. Peça outro.",
    "Cópia guardada · leitura offline",
    "Guias guardados",
    "As minhas cópias",
    "Versão online",
    "Disponíveis neste dispositivo. As atualizações precisam de ligação.",
    "Eliminar cópia local",
    "Este guia não foi guardado neste dispositivo.",
    "O guia guardado não está disponível.",
    "É necessária ligação para enviar um pedido, mensagem ou comentário. Nada foi enviado.",
  ],
};
export function addV1Copy(translations: Record<Locale, Record<string, string>>) {
  for (const locale of Object.keys(copy) as Locale[])
    keys.forEach((key, index) => {
      translations[locale][key] = copy[locale][index] ?? "";
    });
}
