import type { Locale } from "./i18n";

const keys = [
  "section.welcome",
  "manager.sortLabel",
  "manager.sortAZ",
  "manager.sortZA",
  "manager.sortNewest",
  "manager.sortOldest",
  "manager.propertyMedia",
  "manager.guestPreview",
  "manager.coverAlt",
  "manager.changeCover",
  "manager.hostbuddyAmbience",
  "manager.mainPhoto",
  "manager.setMainPhoto",
  "manager.replace",
  "manager.movePhotoForward",
  "manager.movePhotoBack",
  "manager.deletePhoto",
  "manager.addPhotos",
  "manager.replaceVideo",
  "manager.cancel",
  "manager.videoPreparing",
  "manager.videoOptimizing",
  "manager.videoUploading",
  "manager.mediaLimits",
  "manager.retrySave",
  "manager.propertyName",
  "manager.propertyNameError",
  "qr.title",
] as const;

const copy: Record<Locale, readonly string[]> = {
  fr: [
    "Bienvenue",
    "Trier",
    "A → Z",
    "Z → A",
    "Plus récents",
    "Plus anciens",
    "Médias du logement",
    "Aperçu voyageur",
    "Couverture du logement",
    "Modifier la couverture",
    "Ambiance HostBuddy",
    "Photo principale",
    "Définir comme principale",
    "Remplacer",
    "Avancer la photo",
    "Reculer la photo",
    "Supprimer la photo",
    "Ajouter des photos",
    "Remplacer la vidéo",
    "Annuler",
    "Préparation vidéo…",
    "Optimisation vidéo · {percent} %",
    "Envoi de la vidéo…",
    "Photos : 10 Mo max. Vidéo : 50 Mo max., 90 secondes. Glissez les photos pour les réordonner.",
    "Enregistrement à réessayer",
    "Nom de l’hébergement",
    "Le nom n’a pas pu être enregistré. Réessayez.",
    "QR code",
  ],
  en: [
    "Welcome",
    "Sort",
    "A → Z",
    "Z → A",
    "Newest first",
    "Oldest first",
    "Property media",
    "Guest preview",
    "Property cover",
    "Change cover",
    "HostBuddy atmosphere",
    "Main photo",
    "Set as main photo",
    "Replace",
    "Move photo forward",
    "Move photo back",
    "Delete photo",
    "Add photos",
    "Replace video",
    "Cancel",
    "Preparing video…",
    "Optimizing video · {percent}%",
    "Uploading video…",
    "Photos: 10 MB max. Video: 50 MB max., 90 seconds. Drag photos to reorder them.",
    "Save needs retrying",
    "Property name",
    "The name could not be saved. Please try again.",
    "QR code",
  ],
  es: [
    "Bienvenida",
    "Ordenar",
    "A → Z",
    "Z → A",
    "Más recientes",
    "Más antiguos",
    "Contenido multimedia",
    "Vista del huésped",
    "Portada del alojamiento",
    "Cambiar portada",
    "Ambiente HostBuddy",
    "Foto principal",
    "Definir como principal",
    "Reemplazar",
    "Adelantar foto",
    "Atrasar foto",
    "Eliminar foto",
    "Añadir fotos",
    "Reemplazar vídeo",
    "Cancelar",
    "Preparando vídeo…",
    "Optimizando vídeo · {percent}%",
    "Subiendo vídeo…",
    "Fotos: 10 MB máx. Vídeo: 50 MB máx., 90 segundos. Arrastra las fotos para ordenarlas.",
    "Vuelve a intentar guardar",
    "Nombre del alojamiento",
    "No se pudo guardar el nombre. Inténtalo de nuevo.",
    "Código QR",
  ],
  de: [
    "Willkommen",
    "Sortieren",
    "A → Z",
    "Z → A",
    "Neueste zuerst",
    "Älteste zuerst",
    "Medien der Unterkunft",
    "Gästevorschau",
    "Titelbild der Unterkunft",
    "Titelbild ändern",
    "HostBuddy-Ambiente",
    "Hauptfoto",
    "Als Hauptfoto festlegen",
    "Ersetzen",
    "Foto nach vorne",
    "Foto nach hinten",
    "Foto löschen",
    "Fotos hinzufügen",
    "Video ersetzen",
    "Abbrechen",
    "Video wird vorbereitet…",
    "Video wird optimiert · {percent}%",
    "Video wird hochgeladen…",
    "Fotos: max. 10 MB. Video: max. 50 MB, 90 Sekunden. Fotos zum Sortieren ziehen.",
    "Speichern erneut versuchen",
    "Name der Unterkunft",
    "Der Name konnte nicht gespeichert werden. Bitte erneut versuchen.",
    "QR-Code",
  ],
  it: [
    "Benvenuto",
    "Ordina",
    "A → Z",
    "Z → A",
    "Più recenti",
    "Meno recenti",
    "Media dell’alloggio",
    "Anteprima ospite",
    "Copertina dell’alloggio",
    "Cambia copertina",
    "Atmosfera HostBuddy",
    "Foto principale",
    "Imposta come principale",
    "Sostituisci",
    "Sposta foto avanti",
    "Sposta foto indietro",
    "Elimina foto",
    "Aggiungi foto",
    "Sostituisci video",
    "Annulla",
    "Preparazione video…",
    "Ottimizzazione video · {percent}%",
    "Caricamento video…",
    "Foto: max 10 MB. Video: max 50 MB, 90 secondi. Trascina le foto per riordinarle.",
    "Riprova a salvare",
    "Nome dell’alloggio",
    "Impossibile salvare il nome. Riprova.",
    "Codice QR",
  ],
  pt: [
    "Boas-vindas",
    "Ordenar",
    "A → Z",
    "Z → A",
    "Mais recentes",
    "Mais antigos",
    "Média do alojamento",
    "Pré-visualização do hóspede",
    "Capa do alojamento",
    "Alterar capa",
    "Ambiente HostBuddy",
    "Fotografia principal",
    "Definir como principal",
    "Substituir",
    "Avançar fotografia",
    "Recuar fotografia",
    "Eliminar fotografia",
    "Adicionar fotografias",
    "Substituir vídeo",
    "Cancelar",
    "A preparar vídeo…",
    "A otimizar vídeo · {percent}%",
    "A enviar vídeo…",
    "Fotografias: máx. 10 MB. Vídeo: máx. 50 MB, 90 segundos. Arraste para reordenar.",
    "Tentar guardar novamente",
    "Nome do alojamento",
    "Não foi possível guardar o nome. Tente novamente.",
    "Código QR",
  ],
};

export function addVisualPolishCopy(translations: Record<Locale, Record<string, string>>) {
  for (const locale of Object.keys(copy) as Locale[])
    keys.forEach((key, index) => {
      translations[locale][key] = copy[locale][index] ?? "";
    });
}
