import { createFileRoute, notFound, Link } from "@tanstack/react-router";
import { ArrowLeft, Mail, MessageCircle, Phone, Send, Star, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useMemo, useState } from "react";
import { getPublicGuide, type PublicSection } from "@/lib/data/public-guide.functions";
import { LanguageSelect } from "@/components/i18n/LanguageSelect";
import { useI18n } from "@/lib/i18n";
import arrivalAsset from "@/assets/hostbuddy-arrival.jpg.asset.json";
import breakfastAsset from "@/assets/hostbuddy-breakfast.jpg.asset.json";
import spaAsset from "@/assets/hostbuddy-spa.jpg.asset.json";

export const Route = createFileRoute("/l/$slug")({
  loader: async ({ params }) => { const guide = await getPublicGuide({ data: { slug: params.slug } }); if (!guide) throw notFound(); return guide; },
  head: ({ loaderData }) => { const title = loaderData ? `${loaderData.name} — Guide voyageur HostBuddy` : "Guide indisponible — HostBuddy"; const desc = loaderData ? `Toutes les informations utiles pour votre séjour à ${loaderData.name}.` : "Ce guide n'est pas disponible."; return { meta: [{ title }, { name: "description", content: desc }, { property: "og:title", content: title }, { property: "og:description", content: desc }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }, ...(loaderData ? [] : [{ name: "robots", content: "noindex" }])] }; },
  notFoundComponent: Unavailable, errorComponent: Unavailable, component: GuestPage,
});

function Unavailable() { const { t } = useI18n(); return <main className="mx-auto max-w-md px-5 py-16 text-center"><span className="text-5xl" aria-hidden>🏡</span><h1 className="mt-4 text-3xl font-semibold">{t("guest.unavailable")}</h1><p className="mt-3 text-lg">{t("guest.unavailableD")}</p><Link to="/" className="btn btn-secondary mt-8">{t("guest.discover")}</Link></main>; }

function localizedSection(section: PublicSection, locale: string) {
  const translated = section.translations?.find((item) => item.locale === locale && !item.isStale);
  return translated ? { ...section, title: translated.title, content: translated.content } : section;
}
const displayTitle = (title: string) => title.replace(/^[^\p{L}\p{N}]+/u, "");

function GuestPage() {
  const guide = Route.useLoaderData();
  const { locale, t } = useI18n();
  const sections = useMemo(() => guide.sections.map((section) => localizedSection(section, locale)), [guide.sections, locale]);
  const [openKey, setOpenKey] = useState<string | null>(null);
  const [messageOpen, setMessageOpen] = useState(false);
  const open = sections.find((section) => section.key === openKey) ?? null;
  const contact = sections.find((section) => section.key === "contact");
  if (open) return <main className="mx-auto min-h-screen max-w-3xl bg-background px-4 py-5 sm:px-8"><div className="flex items-center justify-between"><Button onClick={() => setOpenKey(null)} variant="ghost" className="min-h-12 px-2 text-primary"><ArrowLeft/>{t("guest.back")}</Button><LanguageSelect compact /></div><h1 className="mt-5 text-4xl font-semibold sm:text-5xl">{displayTitle(open.title)}</h1><div className="mt-6 grid gap-4 md:grid-cols-2"><div className="space-y-4">{open.content.items?.map((item, index) => <div key={`${item.label}-${index}`} className="surface p-5">{item.label && <p className="text-sm font-bold text-muted-foreground">{item.label}</p>}<p className="mt-2 whitespace-pre-line text-lg leading-relaxed">{item.text}</p></div>)}{open.key === "services" && <ServicePreview />}{open.key === "contact" && <ContactButtons section={open}/>}</div>{open.media?.length ? <SectionMedia section={open}/> : null}</div></main>;
  const hero = sections.flatMap((section) => section.media ?? []).find((item) => item.type === "image" && item.url)?.url ?? arrivalAsset.url;
  return <main className="mx-auto min-h-screen max-w-3xl bg-background pb-28 shadow-soft">
    <div className="relative h-[min(25rem,46dvh)] min-h-72 overflow-hidden"><img src={hero} alt={guide.name} width={1536} height={1024} className="h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-ink/95 via-ink/25 to-ink/55"/><div className="absolute right-4 top-4"><LanguageSelect compact /></div><div className="absolute inset-x-5 bottom-6 text-ink-foreground sm:inset-x-8"><p className="text-sm font-bold text-ink-foreground/90">{t("guest.welcome")}</p><h1 className="mt-1 text-4xl font-semibold sm:text-5xl">{guide.name}</h1><p className="mt-2 text-sm font-semibold text-ink-foreground/90">{t("guest.noInstall")}</p></div></div>
    <div className="px-4 py-6 sm:px-8"><h2 className="text-2xl font-semibold">{t("guest.stay")}</h2>{sections.length === 0 ? <p className="mt-4 text-lg">{t("guest.empty")}</p> : <div className="mt-5 grid grid-cols-2 gap-3 md:grid-cols-3">{sections.slice(0, 6).map((section, index) => { const cover=section.media?.find((item)=>item.type==="image"&&item.url)?.url; return <button key={section.key} onClick={() => setOpenKey(section.key)} className={`relative min-h-36 overflow-hidden rounded-lg border bg-card p-4 text-left text-lg font-bold shadow-sm transition hover:border-primary ${index === 0 ? "col-span-2 md:col-span-1" : ""}`}><span className={`relative z-10 ${cover?"text-ink-foreground drop-shadow":""}`}>{displayTitle(section.title)}</span>{cover&&<><img src={cover} alt="" loading="lazy" className="absolute inset-0 h-full w-full object-cover"/><span className="absolute inset-0 bg-gradient-to-t from-ink/85 to-ink/10"/></>}{section.key === "services" && !cover && <img src={breakfastAsset.url} alt="" loading="lazy" width={1200} height={912} className="absolute inset-0 h-full w-full object-cover opacity-20"/>}</button>})}</div>}
      {sections.length > 6 && <div className="mt-3 grid gap-3">{sections.slice(6).map((section) => <button key={section.key} onClick={() => setOpenKey(section.key)} className="min-h-14 rounded-lg border bg-card px-4 text-left font-semibold">{displayTitle(section.title)}</button>)}</div>}
      {guide.review && guide.review.destinations.length > 0 && <section className="mt-8 rounded-lg bg-accent p-6"><Star className="h-7 w-7 text-accent-foreground"/><h2 className="mt-3 text-2xl font-semibold">{guide.review.title}</h2><p className="mt-2 text-accent-foreground">{guide.review.message}</p><div className="mt-4 grid gap-2">{guide.review.destinations.map((destination) => <a key={`${destination.label}-${destination.url}`} href={destination.url} target="_blank" rel="noreferrer" className="btn btn-primary">{destination.label}</a>)}</div></section>}
      {guide.messagingEnabled && <Button className="mt-8 min-h-14 w-full rounded-full text-base" onClick={()=>setMessageOpen(true)}><MessageCircle/>Envoyer un message</Button>}
    </div>
    {contact && <div className="fixed inset-x-0 bottom-0 z-20 mx-auto max-w-3xl border-t bg-background/95 p-3 backdrop-blur"><ContactButtons section={contact}/></div>}
    {messageOpen && <MessageDrawer slug={Route.useParams().slug} onClose={()=>setMessageOpen(false)}/>} 
  </main>;
}

function SectionMedia({section}:{section:PublicSection}){return <div className="space-y-4">{section.media?.map((item)=>item.url&&(item.type==="image"?<figure key={item.id}><img src={item.url} alt={item.altText??""} loading="lazy" className="max-h-[32rem] w-full rounded-lg object-cover"/>{item.caption&&<figcaption className="mt-1 text-sm text-muted-foreground">{item.caption}</figcaption>}</figure>:<figure key={item.id}><video src={item.url} controls preload="metadata" className="max-h-[32rem] w-full rounded-lg bg-ink"/>{item.caption&&<figcaption className="mt-1 text-sm text-muted-foreground">{item.caption}</figcaption>}</figure>))}</div>}

function MessageDrawer({slug,onClose}:{slug:string;onClose:()=>void}){const[name,setName]=useState("");const[contact,setContact]=useState("");const[message,setMessage]=useState("");const[website,setWebsite]=useState("");const[busy,setBusy]=useState(false);const[sent,setSent]=useState(false);const[error,setError]=useState("");return <div className="fixed inset-0 z-50 flex items-end justify-center bg-ink/60 p-0 sm:items-center sm:p-5" role="dialog" aria-modal="true" aria-label="Envoyer un message"><div className="max-h-[92dvh] w-full max-w-lg overflow-y-auto rounded-t-xl bg-background p-5 sm:rounded-xl sm:p-7"><div className="flex items-center justify-between"><h2 className="text-2xl font-semibold">Envoyer un message</h2><Button variant="ghost" size="icon" className="h-12 w-12" aria-label="Fermer" onClick={onClose}><X/></Button></div>{sent?<div className="py-10 text-center"><p className="text-4xl">✓</p><p className="mt-3 text-xl font-semibold">Message envoyé</p><Button className="mt-6 min-h-12 rounded-full" onClick={onClose}>Fermer</Button></div>:<form className="mt-5 space-y-4" onSubmit={async(e)=>{e.preventDefault();setBusy(true);setError("");try{const r=await fetch("/api/public/messages",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({slug,name,contact,message,website})});const body=await r.json() as {error?:string};if(!r.ok)throw new Error(body.error);setSent(true)}catch(err){setError(err instanceof Error?err.message:"Le message n’a pas pu être envoyé.")}finally{setBusy(false)}}}><label className="block"><span className="mb-1 block font-semibold">Votre nom</span><input className="field" required maxLength={80} value={name} onChange={(e)=>setName(e.target.value)}/></label><label className="block"><span className="mb-1 block font-semibold">E-mail ou téléphone <span className="font-normal text-muted-foreground">(facultatif)</span></span><input className="field" maxLength={160} value={contact} onChange={(e)=>setContact(e.target.value)}/></label><label className="block"><span className="mb-1 block font-semibold">Votre message</span><textarea className="field min-h-36" required maxLength={2000} value={message} onChange={(e)=>setMessage(e.target.value)}/></label><label className="sr-only">Site web<input tabIndex={-1} autoComplete="off" value={website} onChange={(e)=>setWebsite(e.target.value)}/></label>{error&&<p role="alert" className="rounded-lg bg-warning-soft p-3">{error}</p>}<Button className="min-h-14 w-full rounded-full" disabled={busy||!name.trim()||!message.trim()}><Send/> {busy?"Envoi…":"Envoyer"}</Button></form>}</div></div>}

function ServicePreview() { const { t } = useI18n(); return <div className="space-y-3"><div className="grid grid-cols-2 gap-3"><img src={breakfastAsset.url} alt="Petit-déjeuner" loading="lazy" width={1200} height={912} className="h-32 w-full rounded-lg object-cover"/><img src={spaAsset.url} alt="Massage" loading="lazy" width={1200} height={912} className="h-32 w-full rounded-lg object-cover"/></div><p className="text-center text-sm text-muted-foreground">{t("guest.serviceDemo")}</p></div>; }
function ContactButtons({ section }: { section: PublicSection }) { const { t } = useI18n(); const phone = section.content.phones?.[0]; const email = section.content.emails?.[0]; if (!phone && !email) return null; return <div className="grid grid-cols-3 gap-2">{phone && <a className="btn btn-primary px-1 text-sm sm:text-base" href={`tel:${phone}`}><Phone className="h-4 w-4"/>{t("guest.call")}</a>}{phone && <a className="btn btn-secondary px-1 text-sm sm:text-base" href={`https://wa.me/${phone.replace(/\D/g, "")}`} target="_blank" rel="noreferrer"><MessageCircle className="h-4 w-4"/><span className="hidden min-[390px]:inline">WhatsApp</span></a>}{email && <a className="btn btn-secondary px-1 text-sm sm:text-base" href={`mailto:${email}`}><Mail className="h-4 w-4"/>{t("guest.email")}</a>}</div>; }
