import { createFileRoute, notFound, Link } from "@tanstack/react-router";
import { ArrowLeft, Check, Mail, MessageCircle, Phone, Send, ShoppingBag, Star, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useMemo, useState } from "react";
import { getPublicGuide, type PublicSection } from "@/lib/data/public-guide.functions";
import { LanguageSelect } from "@/components/i18n/LanguageSelect";
import { useI18n } from "@/lib/i18n";
import arrivalAsset from "@/assets/hostbuddy-arrival.jpg.asset.json";
import breakfastAsset from "@/assets/hostbuddy-breakfast.jpg.asset.json";
import spaAsset from "@/assets/hostbuddy-spa.jpg.asset.json";

export const Route = createFileRoute("/l/$slug")({
  loader: async ({ params }) => { const guide = await getPublicGuide({ data: { slug: params.slug } }); if (!guide) throw notFound(); return guide; },
  head: ({ loaderData }) => { const title = loaderData ? `${loaderData.name} — Guide voyageur HostBuddy` : "Guide indisponible — HostBuddy"; const desc = loaderData ? `Toutes les informations utiles pour votre séjour à ${loaderData.name}.` : "Ce guide n'est pas disponible."; return { meta: [{ title }, { name: "description", content: desc }, { property: "og:title", content: title }, { property: "og:description", content: desc }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }, ...(loaderData ? [] : [{ name: "robots", content: "noindex" }])] }; },
  notFoundComponent: Unavailable, errorComponent: Unavailable, component: GuestPage,
});

function Unavailable() { const { t } = useI18n(); return <main className="mx-auto max-w-md px-5 py-16 text-center"><span className="text-5xl" aria-hidden>🏡</span><h1 className="mt-4 text-3xl font-semibold">{t("guest.unavailable")}</h1><p className="mt-3 text-lg">{t("guest.unavailableD")}</p><Link to="/" className="btn btn-secondary mt-8">{t("guest.discover")}</Link></main>; }

function localizedSection(section: PublicSection, locale: string) {
  const translated = section.translations?.find((item) => item.locale === locale && !item.isStale);
  return translated ? { ...section, title: translated.title, content: translated.content } : section;
}
const displayTitle = (title: string) => title.replace(/^[^\p{L}\p{N}]+/u, "");

function GuestPage() {
  const guide = Route.useLoaderData();
  const { locale, t } = useI18n();
  const sections = useMemo(() => guide.sections.map((section) => localizedSection(section, locale)), [guide.sections, locale]);
  const [openKey, setOpenKey] = useState<string | null>(null);
  const [messageOpen, setMessageOpen] = useState(false);
  const [serviceId, setServiceId] = useState<string|null>(null);
  const [feedbackOpen,setFeedbackOpen]=useState(false);
  const open = sections.find((section) => section.key === openKey) ?? null;
  const contact = sections.find((section) => section.key === "contact");
   if (open) return <main className="mx-auto min-h-screen max-w-3xl bg-background px-4 py-5 sm:px-8"><div className="flex items-center justify-between"><Button onClick={() => setOpenKey(null)} variant="ghost" className="min-h-12 px-2 text-primary"><ArrowLeft/>{t("guest.back")}</Button><LanguageSelect compact /></div><div className="mt-5 flex items-center gap-3 border-b pb-5"><span className="grid h-14 w-14 shrink-0 place-items-center rounded-xl bg-secondary text-2xl">{open.icon??"📌"}</span><h1 className="text-4xl font-semibold sm:text-5xl">{displayTitle(open.title)}</h1></div><div className="mt-6 grid gap-5 md:grid-cols-2"><div className="space-y-4">{open.content.items?.map((item, index) => <div key={`${item.label}-${index}`} className="rounded-xl bg-muted p-5">{item.label && <p className="text-sm font-bold text-muted-foreground">{item.label}</p>}<p className="mt-1 whitespace-pre-line text-lg leading-relaxed">{item.text}</p></div>)}{open.key === "services" && <ServiceList services={guide.services??[]} onRequest={setServiceId}/>} {open.key === "contact" && <ContactButtons section={open}/>}</div>{open.media?.length ? <SectionMedia section={open}/> : null}</div>{serviceId&&<OrderDrawer slug={Route.useParams().slug} service={(guide.services??[]).find(item=>item.id===serviceId)!} onClose={()=>setServiceId(null)}/>}</main>;
  const hero = sections.flatMap((section) => section.media ?? []).find((item) => item.type === "image" && item.url)?.url ?? arrivalAsset.url;
  return <main className="mx-auto min-h-screen max-w-3xl bg-background pb-28 shadow-soft">
    <div className="relative h-[min(25rem,46dvh)] min-h-72 overflow-hidden"><img src={hero} alt={guide.name} width={1536} height={1024} className="h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-ink/95 via-ink/25 to-ink/55"/><div className="absolute right-4 top-4"><LanguageSelect compact /></div><div className="absolute inset-x-5 bottom-6 text-ink-foreground sm:inset-x-8"><p className="text-sm font-bold text-ink-foreground/90">{t("guest.welcome")}</p><h1 className="mt-1 text-4xl font-semibold sm:text-5xl">{guide.name}</h1><p className="mt-2 text-sm font-semibold text-ink-foreground/90">{t("guest.noInstall")}</p></div></div>
     <div className="px-4 py-6 sm:px-8"><h2 className="text-2xl font-semibold">{t("guest.stay")}</h2>{sections.length === 0 ? <p className="mt-4 text-lg">{t("guest.empty")}</p> : <div className="mt-5 grid gap-2 sm:grid-cols-2">{sections.slice(0, 6).map((section) => { const cover=section.media?.find((item)=>item.type==="image"&&item.url)?.url; return <button key={section.key} onClick={() => setOpenKey(section.key)} className="group relative flex min-h-16 items-center gap-3 overflow-hidden rounded-xl border bg-card px-4 text-left font-bold shadow-sm transition hover:border-primary"><span className={`relative z-10 grid h-10 w-10 shrink-0 place-items-center rounded-lg ${cover?"bg-ink/45":"bg-secondary"}`}>{section.icon??"📌"}</span><span className={`relative z-10 ${cover?"text-ink-foreground":""}`}>{displayTitle(section.title)}</span>{cover&&<><img src={cover} alt="" loading="lazy" className="absolute inset-0 h-full w-full object-cover"/><span className="absolute inset-0 bg-gradient-to-r from-ink/90 via-ink/55 to-ink/10"/></>}</button>})}</div>}
       {sections.length > 6 && <div className="mt-5 rounded-xl bg-muted p-2"><p className="px-3 py-2 text-sm font-bold text-muted-foreground">Plus d’informations</p>{sections.slice(6).filter(s=>s.key!=="contact").map((section) => <button key={section.key} onClick={() => setOpenKey(section.key)} className="flex min-h-14 w-full items-center gap-3 rounded-lg px-3 text-left font-semibold hover:bg-card"><span className="text-xl">{section.icon??"📌"}</span>{displayTitle(section.title)}</button>)}</div>}
       <Button variant="outline" className="mt-8 min-h-14 w-full rounded-full" onClick={()=>setFeedbackOpen(true)}><Star/>Envoyer un retour privé</Button>
       {guide.review && guide.review.destinations.length > 0 && <section className="mt-4 rounded-xl bg-accent p-6"><Star className="h-7 w-7 text-accent-foreground"/><h2 className="mt-3 text-2xl font-semibold">{guide.review.title}</h2><p className="mt-2 text-accent-foreground">{guide.review.message}</p><div className="mt-4 grid gap-2">{guide.review.destinations.map((destination) => <a key={`${destination.label}-${destination.url}`} href={destination.url} target="_blank" rel="noreferrer" className="btn btn-primary">{destination.label}</a>)}</div></section>}
      {guide.messagingEnabled && <Button className="mt-8 min-h-14 w-full rounded-full text-base" onClick={()=>setMessageOpen(true)}><MessageCircle/>Envoyer un message</Button>}
    </div>
    {contact && <div className="fixed inset-x-0 bottom-0 z-20 mx-auto max-w-3xl border-t bg-background/95 p-3 backdrop-blur"><ContactButtons section={contact}/></div>}
    {messageOpen && <MessageDrawer slug={Route.useParams().slug} onClose={()=>setMessageOpen(false)}/>} 
     {feedbackOpen&&<FeedbackDrawer slug={Route.useParams().slug} onClose={()=>setFeedbackOpen(false)}/>} 
  </main>;
}

function SectionMedia({section}:{section:PublicSection}){return <div className="space-y-4">{section.media?.map((item)=>item.url&&(item.type==="image"?<figure key={item.id}><img src={item.url} alt={item.altText??""} loading="lazy" className="max-h-[32rem] w-full rounded-lg object-cover"/>{item.caption&&<figcaption className="mt-1 text-sm text-muted-foreground">{item.caption}</figcaption>}</figure>:<figure key={item.id}><video src={item.url} controls preload="metadata" className="max-h-[32rem] w-full rounded-lg bg-ink"/>{item.caption&&<figcaption className="mt-1 text-sm text-muted-foreground">{item.caption}</figcaption>}</figure>))}</div>}

function MessageDrawer({slug,onClose}:{slug:string;onClose:()=>void}){const[name,setName]=useState("");const[contact,setContact]=useState("");const[message,setMessage]=useState("");const[website,setWebsite]=useState("");const[busy,setBusy]=useState(false);const[sent,setSent]=useState(false);const[error,setError]=useState("");return <div className="fixed inset-0 z-50 flex items-end justify-center bg-ink/60 p-0 sm:items-center sm:p-5" role="dialog" aria-modal="true" aria-label="Envoyer un message"><div className="max-h-[92dvh] w-full max-w-lg overflow-y-auto rounded-t-xl bg-background p-5 sm:rounded-xl sm:p-7"><div className="flex items-center justify-between"><h2 className="text-2xl font-semibold">Envoyer un message</h2><Button variant="ghost" size="icon" className="h-12 w-12" aria-label="Fermer" onClick={onClose}><X/></Button></div>{sent?<div className="py-10 text-center"><p className="text-4xl">✓</p><p className="mt-3 text-xl font-semibold">Message envoyé</p><Button className="mt-6 min-h-12 rounded-full" onClick={onClose}>Fermer</Button></div>:<form className="mt-5 space-y-4" onSubmit={async(e)=>{e.preventDefault();setBusy(true);setError("");try{const r=await fetch("/api/public/messages",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({slug,name,contact,message,website})});const body=await r.json() as {error?:string};if(!r.ok)throw new Error(body.error);setSent(true)}catch(err){setError(err instanceof Error?err.message:"Le message n’a pas pu être envoyé.")}finally{setBusy(false)}}}><label className="block"><span className="mb-1 block font-semibold">Votre nom</span><input className="field" required maxLength={80} value={name} onChange={(e)=>setName(e.target.value)}/></label><label className="block"><span className="mb-1 block font-semibold">E-mail ou téléphone <span className="font-normal text-muted-foreground">(facultatif)</span></span><input className="field" maxLength={160} value={contact} onChange={(e)=>setContact(e.target.value)}/></label><label className="block"><span className="mb-1 block font-semibold">Votre message</span><textarea className="field min-h-36" required maxLength={2000} value={message} onChange={(e)=>setMessage(e.target.value)}/></label><label className="sr-only">Site web<input tabIndex={-1} autoComplete="off" value={website} onChange={(e)=>setWebsite(e.target.value)}/></label>{error&&<p role="alert" className="rounded-lg bg-warning-soft p-3">{error}</p>}<Button className="min-h-14 w-full rounded-full" disabled={busy||!name.trim()||!message.trim()}><Send/> {busy?"Envoi…":"Envoyer"}</Button></form>}</div></div>}

function ServiceList({services,onRequest}:{services:NonNullable<ReturnType<typeof Route.useLoaderData>["services"]>;onRequest:(id:string)=>void}){if(!services.length)return <p className="rounded-xl bg-muted p-4 text-muted-foreground">Aucun service disponible pour le moment.</p>;return <div className="space-y-3">{services.map((service,index)=><article key={service.id} className="overflow-hidden rounded-xl border bg-card">{index<2&&<img src={index?spaAsset.url:breakfastAsset.url} alt="" loading="lazy" className="h-28 w-full object-cover"/>}<div className="p-4"><div className="flex justify-between gap-3"><div><p className="font-bold">{service.name}</p><p className="mt-1 text-sm text-muted-foreground">{service.description}</p></div><strong className="shrink-0 text-primary">{Number(service.price).toFixed(2)} €</strong></div><Button className="mt-4 w-full" onClick={()=>onRequest(service.id)}><ShoppingBag/>Demander</Button><p className="mt-2 text-center text-xs text-muted-foreground">Demande de réservation · aucun paiement en ligne</p></div></article>)}</div>}
function ContactButtons({ section }: { section: PublicSection }) { const { t } = useI18n(); const phone = section.content.phones?.[0]; const email = section.content.emails?.[0]; if (!phone && !email) return null; return <div className="grid grid-cols-3 gap-2">{phone && <a className="btn btn-primary px-1 text-sm sm:text-base" href={`tel:${phone}`}><Phone className="h-4 w-4"/>{t("guest.call")}</a>}{phone && <a className="btn btn-secondary px-1 text-sm sm:text-base" href={`https://wa.me/${phone.replace(/\D/g, "")}`} target="_blank" rel="noreferrer"><MessageCircle className="h-4 w-4"/><span className="hidden min-[390px]:inline">WhatsApp</span></a>}{email && <a className="btn btn-secondary px-1 text-sm sm:text-base" href={`mailto:${email}`}><Mail className="h-4 w-4"/>{t("guest.email")}</a>}</div>; }

function OrderDrawer({slug,service,onClose}:{slug:string;service:{id:string;name:string;price:number};onClose:()=>void}){const[name,setName]=useState("");const[contact,setContact]=useState("");const[quantity,setQuantity]=useState(1);const[busy,setBusy]=useState(false);const[sent,setSent]=useState(false);const[error,setError]=useState("");return <Drawer title={service.name} onClose={onClose}>{sent?<Success text="Demande envoyée. Votre hôte va la confirmer." onClose={onClose}/>:<form className="space-y-4" onSubmit={async e=>{e.preventDefault();setBusy(true);setError("");try{const r=await fetch("/api/public/orders",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({slug,serviceId:service.id,name,contact,quantity,requestedFor:null,website:""})});const body=await r.json();if(!r.ok)throw new Error(body.error);setSent(true)}catch(e){setError(e instanceof Error?e.message:"Envoi impossible.")}finally{setBusy(false)}}}><p className="rounded-xl bg-warning-soft p-3 text-sm">Il s’agit d’une demande non payée. Votre hôte doit la confirmer.</p><label className="block"><span className="mb-1 block font-semibold">Votre nom</span><input className="field" required maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label><label className="block"><span className="mb-1 block font-semibold">E-mail ou téléphone <span className="font-normal text-muted-foreground">(facultatif)</span></span><input className="field" maxLength={160} value={contact} onChange={e=>setContact(e.target.value)}/></label><label className="block"><span className="mb-1 block font-semibold">Quantité</span><input className="field" type="number" min={1} max={20} value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></label><p className="text-xl font-bold">Total demandé : {(Number(service.price)*quantity).toFixed(2)} €</p>{error&&<p role="alert" className="rounded-xl bg-warning-soft p-3">{error}</p>}<Button className="w-full" disabled={busy}>{busy?"Envoi…":"Envoyer la demande"}</Button></form>}</Drawer>}
function FeedbackDrawer({slug,onClose}:{slug:string;onClose:()=>void}){const[rating,setRating]=useState(5);const[name,setName]=useState("");const[comment,setComment]=useState("");const[busy,setBusy]=useState(false);const[sent,setSent]=useState(false);return <Drawer title="Votre retour privé" onClose={onClose}>{sent?<Success text="Merci, votre retour a été transmis directement à l’équipe." onClose={onClose}/>:<form className="space-y-4" onSubmit={async e=>{e.preventDefault();setBusy(true);const r=await fetch("/api/public/feedback",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({slug,name,rating,comment,website:""})});setBusy(false);if(r.ok)setSent(true)}}><p className="text-muted-foreground">Ce message reste privé. Les liens d’avis externes sont proposés séparément.</p><fieldset><legend className="font-semibold">Note</legend><div className="mt-2 flex gap-1">{[1,2,3,4,5].map(n=><button type="button" key={n} aria-label={`${n} étoiles`} onClick={()=>setRating(n)} className="h-12 w-12"><Star className={`mx-auto ${n<=rating?"fill-primary text-primary":"text-border"}`}/></button>)}</div></fieldset><label className="block"><span className="mb-1 block font-semibold">Votre nom <span className="font-normal text-muted-foreground">(facultatif)</span></span><input className="field" maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label><label className="block"><span className="mb-1 block font-semibold">Votre message</span><textarea className="field min-h-32" maxLength={2000} value={comment} onChange={e=>setComment(e.target.value)}/></label><Button className="w-full" disabled={busy}>{busy?"Envoi…":"Envoyer mon retour"}</Button></form>}</Drawer>}
function Drawer({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-50 flex items-end justify-center bg-ink/60 sm:items-center sm:p-5" role="dialog" aria-modal="true"><div className="max-h-[92dvh] w-full max-w-lg overflow-y-auto rounded-t-2xl bg-background p-5 pb-[calc(1.25rem+env(safe-area-inset-bottom))] sm:rounded-2xl"><div className="mb-5 flex items-center justify-between"><h2 className="text-2xl font-semibold">{title}</h2><Button variant="ghost" size="icon" className="h-12 w-12" onClick={onClose}><X/></Button></div>{children}</div></div>}
function Success({text,onClose}:{text:string;onClose:()=>void}){return <div className="py-8 text-center"><Check className="mx-auto h-10 w-10 text-success"/><p className="mt-3 text-lg font-semibold">{text}</p><Button className="mt-6" onClick={onClose}>Fermer</Button></div>}
