import { createFileRoute, Link } from "@tanstack/react-router";
import { queryOptions, useMutation, useQueryClient, useSuspenseQuery } from "@tanstack/react-query";
import { ArrowLeft, Check, Star } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Loading, FriendlyError } from "@/components/app/Friendly";
import { useOrg, orgQuery } from "@/components/app/useOrg";
import { useI18n } from "@/lib/i18n";
import { listFeedback, markFeedbackRead } from "@/lib/data/operations";
const feedbackQuery=(orgId:string)=>queryOptions({queryKey:["feedback",orgId],queryFn:()=>listFeedback(orgId),staleTime:15_000});
export const Route=createFileRoute("/_authenticated/app/feedback")({head:()=>({meta:[{title:"Retours voyageurs — HostBuddy"},{name:"description",content:"Retours privés de vos voyageurs."},{property:"og:title",content:"Retours voyageurs — HostBuddy"},{property:"og:description",content:"Retours privés de vos voyageurs."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"},{name:"robots",content:"noindex"}]}),loader:async({context})=>{const org=await context.queryClient.ensureQueryData(orgQuery);await context.queryClient.ensureQueryData(feedbackQuery(org.id));},pendingComponent:Loading,errorComponent:FriendlyError,component:FeedbackPage});
function FeedbackPage(){const{t,locale}=useI18n();const org=useOrg();const qc=useQueryClient();const{data}=useSuspenseQuery(feedbackQuery(org.id));const mark=useMutation({mutationFn:markFeedbackRead,onSuccess:()=>qc.invalidateQueries({queryKey:["feedback",org.id]})});return <div className="py-6"><Link to="/app" className="inline-flex min-h-12 items-center gap-2 font-semibold text-primary"><ArrowLeft/>{t("ops.back")}</Link><p className="mt-2 font-bold text-primary">{t("feedback.eyebrow")}</p><h1 className="text-4xl font-semibold">{t("feedback.managerTitle")}</h1><p className="mt-2 text-muted-foreground">{t("feedback.managerDesc")}</p><div className="mt-7 grid gap-3 lg:grid-cols-2">{data.map(item=><article key={item.id} className={`surface p-5 ${!item.is_read?"border-l-4 border-l-primary":""}`}><div className="flex items-start justify-between gap-3"><div><p className="font-bold">{item.properties?.name}</p><p className="text-sm text-muted-foreground">{item.guest_name||t("feedback.anonymous")} · {new Intl.DateTimeFormat(locale,{dateStyle:"medium"}).format(new Date(item.created_at))}</p></div><span className="flex gap-0.5" aria-label={`${item.rating} / 5`}>{[1,2,3,4,5].map(n=><Star key={n} className={`h-4 w-4 ${n<=item.rating?"fill-primary text-primary":"text-border"}`}/>)}</span></div><p className="mt-4 whitespace-pre-line leading-relaxed">{item.comment||t("feedback.noComment")}</p>{!item.is_read&&<Button variant="outline" className="mt-4" onClick={()=>mark.mutate(item.id)}><Check/>{t("feedback.markRead")}</Button>}</article>)}{!data.length&&<div className="surface p-6 text-muted-foreground">{t("feedback.emptyManager")}</div>}</div></div>}