/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as GuidePreviewRouteImport } from './routes/guide-preview'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as ApiBillingSyncRouteImport } from './routes/api/billing-sync'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe-webhook'
import { Route as LSlugRouteImport } from './routes/l.$slug'
import { Route as PayTokenRouteImport } from './routes/pay.$token'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppConnectionsRouteImport } from './routes/_authenticated/app.connections'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/app.dashboard'
import { Route as AuthenticatedAppFeedbackRouteImport } from './routes/_authenticated/app.feedback'
import { Route as AuthenticatedAppImportGuestyRouteImport } from './routes/_authenticated/app.import-guesty'
import { Route as AuthenticatedAppImportTextRouteImport } from './routes/_authenticated/app.import-text'
import { Route as AuthenticatedAppImportUrlRouteImport } from './routes/_authenticated/app.import-url'
import { Route as AuthenticatedAppManualRouteImport } from './routes/_authenticated/app.manual'
import { Route as AuthenticatedAppMessagesRouteImport } from './routes/_authenticated/app.messages'
import { Route as AuthenticatedAppNewRouteImport } from './routes/_authenticated/app.new'
import { Route as AuthenticatedAppOrdersRouteImport } from './routes/_authenticated/app.orders'
import { Route as AuthenticatedAppPaymentsRouteImport } from './routes/_authenticated/app.payments'
import { Route as AuthenticatedAppTeamRouteImport } from './routes/_authenticated/app.team'
import { Route as ApiPublicCheckoutRouteImport } from './routes/api/public/checkout'
import { Route as ApiPublicFeedbackRouteImport } from './routes/api/public/feedback'
import { Route as ApiPublicMessagesRouteImport } from './routes/api/public/messages'
import { Route as ApiPublicOrdersRouteImport } from './routes/api/public/orders'
import { Route as ApiPublicPaymentInfoRouteImport } from './routes/api/public/payment-info'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as AuthenticatedAppMessagesIdRouteImport } from './routes/_authenticated/app.messages_.$id'
import { Route as AuthenticatedAppPIdRouteImport } from './routes/_authenticated/app.p.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidePreviewRoute = GuidePreviewRouteImport.update({
  id: '/guide-preview',
  path: '/guide-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiBillingSyncRoute = ApiBillingSyncRouteImport.update({
  id: '/api/billing-sync',
  path: '/api/billing-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe-webhook',
  path: '/api/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LSlugRoute = LSlugRouteImport.update({
  id: '/l/$slug',
  path: '/l/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PayTokenRoute = PayTokenRouteImport.update({
  id: '/pay/$token',
  path: '/pay/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppConnectionsRoute =
  AuthenticatedAppConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFeedbackRoute =
  AuthenticatedAppFeedbackRouteImport.update({
    id: '/feedback',
    path: '/feedback',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppImportGuestyRoute =
  AuthenticatedAppImportGuestyRouteImport.update({
    id: '/import-guesty',
    path: '/import-guesty',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppImportTextRoute =
  AuthenticatedAppImportTextRouteImport.update({
    id: '/import-text',
    path: '/import-text',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppImportUrlRoute =
  AuthenticatedAppImportUrlRouteImport.update({
    id: '/import-url',
    path: '/import-url',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppManualRoute = AuthenticatedAppManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMessagesRoute =
  AuthenticatedAppMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppNewRoute = AuthenticatedAppNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppOrdersRoute = AuthenticatedAppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPaymentsRoute =
  AuthenticatedAppPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTeamRoute = AuthenticatedAppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const ApiPublicCheckoutRoute = ApiPublicCheckoutRouteImport.update({
  id: '/api/public/checkout',
  path: '/api/public/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFeedbackRoute = ApiPublicFeedbackRouteImport.update({
  id: '/api/public/feedback',
  path: '/api/public/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMessagesRoute = ApiPublicMessagesRouteImport.update({
  id: '/api/public/messages',
  path: '/api/public/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOrdersRoute = ApiPublicOrdersRouteImport.update({
  id: '/api/public/orders',
  path: '/api/public/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentInfoRoute = ApiPublicPaymentInfoRouteImport.update({
  id: '/api/public/payment-info',
  path: '/api/public/payment-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppMessagesIdRoute =
  AuthenticatedAppMessagesIdRouteImport.update({
    id: '/messages_/$id',
    path: '/messages/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPIdRoute = AuthenticatedAppPIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/guide-preview': typeof GuidePreviewRoute
  '/integrations': typeof IntegrationsRoute
  '/offline': typeof OfflineRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/api/billing-sync': typeof ApiBillingSyncRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/l/$slug': typeof LSlugRoute
  '/pay/$token': typeof PayTokenRoute
  '/app/connections': typeof AuthenticatedAppConnectionsRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/feedback': typeof AuthenticatedAppFeedbackRoute
  '/app/import-guesty': typeof AuthenticatedAppImportGuestyRoute
  '/app/import-text': typeof AuthenticatedAppImportTextRoute
  '/app/import-url': typeof AuthenticatedAppImportUrlRoute
  '/app/manual': typeof AuthenticatedAppManualRoute
  '/app/messages': typeof AuthenticatedAppMessagesRoute
  '/app/new': typeof AuthenticatedAppNewRoute
  '/app/orders': typeof AuthenticatedAppOrdersRoute
  '/app/payments': typeof AuthenticatedAppPaymentsRoute
  '/app/team': typeof AuthenticatedAppTeamRoute
  '/api/public/checkout': typeof ApiPublicCheckoutRoute
  '/api/public/feedback': typeof ApiPublicFeedbackRoute
  '/api/public/messages': typeof ApiPublicMessagesRoute
  '/api/public/orders': typeof ApiPublicOrdersRoute
  '/api/public/payment-info': typeof ApiPublicPaymentInfoRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/messages/$id': typeof AuthenticatedAppMessagesIdRoute
  '/app/p/$id': typeof AuthenticatedAppPIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/guide-preview': typeof GuidePreviewRoute
  '/integrations': typeof IntegrationsRoute
  '/offline': typeof OfflineRoute
  '/api/billing-sync': typeof ApiBillingSyncRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/l/$slug': typeof LSlugRoute
  '/pay/$token': typeof PayTokenRoute
  '/app/connections': typeof AuthenticatedAppConnectionsRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/feedback': typeof AuthenticatedAppFeedbackRoute
  '/app/import-guesty': typeof AuthenticatedAppImportGuestyRoute
  '/app/import-text': typeof AuthenticatedAppImportTextRoute
  '/app/import-url': typeof AuthenticatedAppImportUrlRoute
  '/app/manual': typeof AuthenticatedAppManualRoute
  '/app/messages': typeof AuthenticatedAppMessagesRoute
  '/app/new': typeof AuthenticatedAppNewRoute
  '/app/orders': typeof AuthenticatedAppOrdersRoute
  '/app/payments': typeof AuthenticatedAppPaymentsRoute
  '/app/team': typeof AuthenticatedAppTeamRoute
  '/api/public/checkout': typeof ApiPublicCheckoutRoute
  '/api/public/feedback': typeof ApiPublicFeedbackRoute
  '/api/public/messages': typeof ApiPublicMessagesRoute
  '/api/public/orders': typeof ApiPublicOrdersRoute
  '/api/public/payment-info': typeof ApiPublicPaymentInfoRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/messages/$id': typeof AuthenticatedAppMessagesIdRoute
  '/app/p/$id': typeof AuthenticatedAppPIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/guide-preview': typeof GuidePreviewRoute
  '/integrations': typeof IntegrationsRoute
  '/offline': typeof OfflineRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/api/billing-sync': typeof ApiBillingSyncRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/l/$slug': typeof LSlugRoute
  '/pay/$token': typeof PayTokenRoute
  '/_authenticated/app/connections': typeof AuthenticatedAppConnectionsRoute
  '/_authenticated/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/app/feedback': typeof AuthenticatedAppFeedbackRoute
  '/_authenticated/app/import-guesty': typeof AuthenticatedAppImportGuestyRoute
  '/_authenticated/app/import-text': typeof AuthenticatedAppImportTextRoute
  '/_authenticated/app/import-url': typeof AuthenticatedAppImportUrlRoute
  '/_authenticated/app/manual': typeof AuthenticatedAppManualRoute
  '/_authenticated/app/messages': typeof AuthenticatedAppMessagesRoute
  '/_authenticated/app/new': typeof AuthenticatedAppNewRoute
  '/_authenticated/app/orders': typeof AuthenticatedAppOrdersRoute
  '/_authenticated/app/payments': typeof AuthenticatedAppPaymentsRoute
  '/_authenticated/app/team': typeof AuthenticatedAppTeamRoute
  '/api/public/checkout': typeof ApiPublicCheckoutRoute
  '/api/public/feedback': typeof ApiPublicFeedbackRoute
  '/api/public/messages': typeof ApiPublicMessagesRoute
  '/api/public/orders': typeof ApiPublicOrdersRoute
  '/api/public/payment-info': typeof ApiPublicPaymentInfoRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/messages_/$id': typeof AuthenticatedAppMessagesIdRoute
  '/_authenticated/app/p/$id': typeof AuthenticatedAppPIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/demo'
    | '/guide-preview'
    | '/integrations'
    | '/offline'
    | '/app'
    | '/api/billing-sync'
    | '/api/stripe-webhook'
    | '/l/$slug'
    | '/pay/$token'
    | '/app/connections'
    | '/app/dashboard'
    | '/app/feedback'
    | '/app/import-guesty'
    | '/app/import-text'
    | '/app/import-url'
    | '/app/manual'
    | '/app/messages'
    | '/app/new'
    | '/app/orders'
    | '/app/payments'
    | '/app/team'
    | '/api/public/checkout'
    | '/api/public/feedback'
    | '/api/public/messages'
    | '/api/public/orders'
    | '/api/public/payment-info'
    | '/api/public/stripe-webhook'
    | '/app/'
    | '/app/messages/$id'
    | '/app/p/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/demo'
    | '/guide-preview'
    | '/integrations'
    | '/offline'
    | '/api/billing-sync'
    | '/api/stripe-webhook'
    | '/l/$slug'
    | '/pay/$token'
    | '/app/connections'
    | '/app/dashboard'
    | '/app/feedback'
    | '/app/import-guesty'
    | '/app/import-text'
    | '/app/import-url'
    | '/app/manual'
    | '/app/messages'
    | '/app/new'
    | '/app/orders'
    | '/app/payments'
    | '/app/team'
    | '/api/public/checkout'
    | '/api/public/feedback'
    | '/api/public/messages'
    | '/api/public/orders'
    | '/api/public/payment-info'
    | '/api/public/stripe-webhook'
    | '/app'
    | '/app/messages/$id'
    | '/app/p/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/demo'
    | '/guide-preview'
    | '/integrations'
    | '/offline'
    | '/_authenticated/app'
    | '/api/billing-sync'
    | '/api/stripe-webhook'
    | '/l/$slug'
    | '/pay/$token'
    | '/_authenticated/app/connections'
    | '/_authenticated/app/dashboard'
    | '/_authenticated/app/feedback'
    | '/_authenticated/app/import-guesty'
    | '/_authenticated/app/import-text'
    | '/_authenticated/app/import-url'
    | '/_authenticated/app/manual'
    | '/_authenticated/app/messages'
    | '/_authenticated/app/new'
    | '/_authenticated/app/orders'
    | '/_authenticated/app/payments'
    | '/_authenticated/app/team'
    | '/api/public/checkout'
    | '/api/public/feedback'
    | '/api/public/messages'
    | '/api/public/orders'
    | '/api/public/payment-info'
    | '/api/public/stripe-webhook'
    | '/_authenticated/app/'
    | '/_authenticated/app/messages_/$id'
    | '/_authenticated/app/p/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DemoRoute: typeof DemoRoute
  GuidePreviewRoute: typeof GuidePreviewRoute
  IntegrationsRoute: typeof IntegrationsRoute
  OfflineRoute: typeof OfflineRoute
  ApiBillingSyncRoute: typeof ApiBillingSyncRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  LSlugRoute: typeof LSlugRoute
  PayTokenRoute: typeof PayTokenRoute
  ApiPublicCheckoutRoute: typeof ApiPublicCheckoutRoute
  ApiPublicFeedbackRoute: typeof ApiPublicFeedbackRoute
  ApiPublicMessagesRoute: typeof ApiPublicMessagesRoute
  ApiPublicOrdersRoute: typeof ApiPublicOrdersRoute
  ApiPublicPaymentInfoRoute: typeof ApiPublicPaymentInfoRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide-preview': {
      id: '/guide-preview'
      path: '/guide-preview'
      fullPath: '/guide-preview'
      preLoaderRoute: typeof GuidePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/billing-sync': {
      id: '/api/billing-sync'
      path: '/api/billing-sync'
      fullPath: '/api/billing-sync'
      preLoaderRoute: typeof ApiBillingSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-webhook': {
      id: '/api/stripe-webhook'
      path: '/api/stripe-webhook'
      fullPath: '/api/stripe-webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/l/$slug': {
      id: '/l/$slug'
      path: '/l/$slug'
      fullPath: '/l/$slug'
      preLoaderRoute: typeof LSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$token': {
      id: '/pay/$token'
      path: '/pay/$token'
      fullPath: '/pay/$token'
      preLoaderRoute: typeof PayTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/connections': {
      id: '/_authenticated/app/connections'
      path: '/connections'
      fullPath: '/app/connections'
      preLoaderRoute: typeof AuthenticatedAppConnectionsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/dashboard': {
      id: '/_authenticated/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/feedback': {
      id: '/_authenticated/app/feedback'
      path: '/feedback'
      fullPath: '/app/feedback'
      preLoaderRoute: typeof AuthenticatedAppFeedbackRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/import-guesty': {
      id: '/_authenticated/app/import-guesty'
      path: '/import-guesty'
      fullPath: '/app/import-guesty'
      preLoaderRoute: typeof AuthenticatedAppImportGuestyRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/import-text': {
      id: '/_authenticated/app/import-text'
      path: '/import-text'
      fullPath: '/app/import-text'
      preLoaderRoute: typeof AuthenticatedAppImportTextRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/import-url': {
      id: '/_authenticated/app/import-url'
      path: '/import-url'
      fullPath: '/app/import-url'
      preLoaderRoute: typeof AuthenticatedAppImportUrlRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/manual': {
      id: '/_authenticated/app/manual'
      path: '/manual'
      fullPath: '/app/manual'
      preLoaderRoute: typeof AuthenticatedAppManualRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/messages': {
      id: '/_authenticated/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AuthenticatedAppMessagesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/new': {
      id: '/_authenticated/app/new'
      path: '/new'
      fullPath: '/app/new'
      preLoaderRoute: typeof AuthenticatedAppNewRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/orders': {
      id: '/_authenticated/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AuthenticatedAppOrdersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/payments': {
      id: '/_authenticated/app/payments'
      path: '/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AuthenticatedAppPaymentsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/team': {
      id: '/_authenticated/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AuthenticatedAppTeamRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/checkout': {
      id: '/api/public/checkout'
      path: '/api/public/checkout'
      fullPath: '/api/public/checkout'
      preLoaderRoute: typeof ApiPublicCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/feedback': {
      id: '/api/public/feedback'
      path: '/api/public/feedback'
      fullPath: '/api/public/feedback'
      preLoaderRoute: typeof ApiPublicFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/messages': {
      id: '/api/public/messages'
      path: '/api/public/messages'
      fullPath: '/api/public/messages'
      preLoaderRoute: typeof ApiPublicMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/orders': {
      id: '/api/public/orders'
      path: '/api/public/orders'
      fullPath: '/api/public/orders'
      preLoaderRoute: typeof ApiPublicOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payment-info': {
      id: '/api/public/payment-info'
      path: '/api/public/payment-info'
      fullPath: '/api/public/payment-info'
      preLoaderRoute: typeof ApiPublicPaymentInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/messages_/$id': {
      id: '/_authenticated/app/messages_/$id'
      path: '/messages/$id'
      fullPath: '/app/messages/$id'
      preLoaderRoute: typeof AuthenticatedAppMessagesIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/p/$id': {
      id: '/_authenticated/app/p/$id'
      path: '/p/$id'
      fullPath: '/app/p/$id'
      preLoaderRoute: typeof AuthenticatedAppPIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppConnectionsRoute: typeof AuthenticatedAppConnectionsRoute
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppFeedbackRoute: typeof AuthenticatedAppFeedbackRoute
  AuthenticatedAppImportGuestyRoute: typeof AuthenticatedAppImportGuestyRoute
  AuthenticatedAppImportTextRoute: typeof AuthenticatedAppImportTextRoute
  AuthenticatedAppImportUrlRoute: typeof AuthenticatedAppImportUrlRoute
  AuthenticatedAppManualRoute: typeof AuthenticatedAppManualRoute
  AuthenticatedAppMessagesRoute: typeof AuthenticatedAppMessagesRoute
  AuthenticatedAppNewRoute: typeof AuthenticatedAppNewRoute
  AuthenticatedAppOrdersRoute: typeof AuthenticatedAppOrdersRoute
  AuthenticatedAppPaymentsRoute: typeof AuthenticatedAppPaymentsRoute
  AuthenticatedAppTeamRoute: typeof AuthenticatedAppTeamRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppMessagesIdRoute: typeof AuthenticatedAppMessagesIdRoute
  AuthenticatedAppPIdRoute: typeof AuthenticatedAppPIdRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppConnectionsRoute: AuthenticatedAppConnectionsRoute,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppFeedbackRoute: AuthenticatedAppFeedbackRoute,
  AuthenticatedAppImportGuestyRoute: AuthenticatedAppImportGuestyRoute,
  AuthenticatedAppImportTextRoute: AuthenticatedAppImportTextRoute,
  AuthenticatedAppImportUrlRoute: AuthenticatedAppImportUrlRoute,
  AuthenticatedAppManualRoute: AuthenticatedAppManualRoute,
  AuthenticatedAppMessagesRoute: AuthenticatedAppMessagesRoute,
  AuthenticatedAppNewRoute: AuthenticatedAppNewRoute,
  AuthenticatedAppOrdersRoute: AuthenticatedAppOrdersRoute,
  AuthenticatedAppPaymentsRoute: AuthenticatedAppPaymentsRoute,
  AuthenticatedAppTeamRoute: AuthenticatedAppTeamRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppMessagesIdRoute: AuthenticatedAppMessagesIdRoute,
  AuthenticatedAppPIdRoute: AuthenticatedAppPIdRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DemoRoute: DemoRoute,
  GuidePreviewRoute: GuidePreviewRoute,
  IntegrationsRoute: IntegrationsRoute,
  OfflineRoute: OfflineRoute,
  ApiBillingSyncRoute: ApiBillingSyncRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  LSlugRoute: LSlugRoute,
  PayTokenRoute: PayTokenRoute,
  ApiPublicCheckoutRoute: ApiPublicCheckoutRoute,
  ApiPublicFeedbackRoute: ApiPublicFeedbackRoute,
  ApiPublicMessagesRoute: ApiPublicMessagesRoute,
  ApiPublicOrdersRoute: ApiPublicOrdersRoute,
  ApiPublicPaymentInfoRoute: ApiPublicPaymentInfoRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
